"""Technical authorities for partnership tax provisions.

Covers §704(b) substantial economic effect, §704(c) contributed property,
§707(a)(2)(B) disguised sales, §731-§737 distributions, §751 hot assets,
§754 elections, §743(b) basis adjustments, and related partnership
formation and operation rules.
"""

from .base import TechnicalAuthority

PARTNERSHIP_TAX_AUTHORITIES = [
    # --- Formation ---
    TechnicalAuthority(
        citation="IRC §721(a)",
        authority_type="statute",
        title="Partnership Formation — Nonrecognition",
        year=1954,
        relevance="No gain or loss recognized on contribution of property to partnership in exchange for interest",
        key_holding="No gain or loss shall be recognized to a partnership or to any of its partners in the case of a contribution of property to the partnership in exchange for an interest in the partnership. Exceptions: investment company partnerships (§721(b)), disguised sales (§707(a)(2)(B)), and services for partnership interest (taxable).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["721", "formation", "nonrecognition", "contribution", "partnership"],
    ),
    TechnicalAuthority(
        citation="IRC §723",
        authority_type="statute",
        title="Partnership — Basis of Contributed Property",
        year=1954,
        relevance="Partnership takes carryover basis in contributed property",
        key_holding="The basis of property contributed to a partnership by a partner shall be the adjusted basis of such property to the contributing partner at the time of the contribution (carryover basis). Increased by any gain recognized by the contributing partner.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["723", "carryover basis", "contributed property", "partnership"],
    ),

    # --- Allocations (§704) ---
    TechnicalAuthority(
        citation="IRC §704(b)",
        authority_type="statute",
        title="§704(b) — Allocations — Substantial Economic Effect",
        year=1954,
        relevance="Partnership allocations respected only if they have substantial economic effect",
        key_holding="A partner's distributive share of income, gain, loss, deduction, or credit is determined by the partnership agreement if the allocation has substantial economic effect. If not, the allocation is determined in accordance with the partner's interest in the partnership (PIP).",
        facts_summary="Substantial economic effect requires both 'economic effect' (capital account maintenance, liquidation per capital accounts, deficit restoration obligation) and 'substantiality' (reasonable possibility allocation affects dollar amounts received by partners independent of tax consequences).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["704(b)", "substantial economic effect", "allocations", "capital accounts"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.704-1(b)(2)",
        authority_type="regulation",
        title="§704(b) — Economic Effect and Substantiality Tests",
        year=1985,
        relevance="Three-part test for economic effect; two-part test for substantiality",
        key_holding="Economic effect requires: (1) capital accounts maintained per Reg. §1.704-1(b)(2)(iv), (2) liquidating distributions made per positive capital accounts, (3) partners with deficit capital accounts have unlimited deficit restoration obligation (DRO) — OR meet the 'alternate test' (QIO + minimum gain chargeback). Substantiality: allocation is substantial if there is a reasonable possibility it will affect dollar amounts received by partners independent of tax consequences.",
        facts_summary="The 'alternate test for economic effect' allows partnerships without DROs to use a qualified income offset (QIO). Minimum gain chargeback under §1.704-2 is required for partnerships with nonrecourse debt.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["704(b)", "economic effect", "substantiality", "DRO", "QIO", "capital accounts"],
    ),
    TechnicalAuthority(
        citation="IRC §704(c)(1)(A)",
        authority_type="statute",
        title="§704(c) — Contributed Property Allocations",
        year=1984,
        relevance="Built-in gain/loss on contributed property allocated to contributing partner",
        key_holding="Income, gain, loss, and deduction with respect to property contributed to a partnership by a partner shall be shared among partners so as to take account of the variation between the adjusted tax basis and the FMV of the property at the time of contribution. The contributing partner is allocated the built-in gain or loss.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["704(c)", "contributed property", "built-in gain", "built-in loss", "allocation"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.704-3",
        authority_type="regulation",
        title="§704(c) Methods — Traditional, Curative, Remedial",
        year=1993,
        relevance="Three permissible methods for allocating §704(c) gain/loss",
        key_holding="Three methods for making §704(c) allocations: (1) Traditional method: allocate tax items to eliminate book-tax disparity, subject to 'ceiling rule' limitation. (2) Traditional with curative allocations: use other partnership tax items to correct ceiling rule distortions. (3) Remedial method: create notional tax items to correct ceiling rule distortions. Partnership must use a reasonable method consistently.",
        facts_summary="The ceiling rule limits tax allocations to the partnership's actual tax items. This can create a 'ceiling rule problem' when there is insufficient tax depreciation to match book depreciation. The remedial method fully eliminates this problem by creating offsetting notional items.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["704(c)", "traditional method", "curative", "remedial", "ceiling rule"],
    ),

    # --- Disguised Sales (§707) ---
    TechnicalAuthority(
        citation="IRC §707(a)(2)(B)",
        authority_type="statute",
        title="Disguised Sales — Contribution/Distribution",
        year=1984,
        relevance="Contribution followed by distribution may be recharacterized as a sale",
        key_holding="If a partner contributes property to a partnership and receives a distribution (money or other property) from the partnership, and the transfer and distribution when viewed together are properly characterized as a sale or exchange, the transaction is treated as a sale between the partner and the partnership.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["707", "disguised sale", "contribution", "distribution", "recharacterization"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.707-3",
        authority_type="regulation",
        title="Disguised Sales — Presumptions and Facts/Circumstances",
        year=1992,
        relevance="2-year presumption for disguised sale treatment",
        key_holding="If a partner contributes property and receives a distribution within 2 years, the transactions are presumed to be a sale (rebuttable). Transfers more than 2 years apart are presumed NOT to be a sale. Factors considered: (1) timing and amount of distribution is determinable at contribution, (2) legally enforceable right to distribution, (3) distribution disproportionate to contributed property, (4) partner's right to distributions is secured by contributed property.",
        facts_summary="Debt-financed distributions: partnership assumption of contributing partner's debt (or debt allocated under §752) within 2 years is treated as consideration received. Qualified liabilities (in place >2 years) are generally excluded from disguised sale treatment.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["707", "disguised sale", "2-year presumption", "qualified liabilities"],
    ),

    # --- Distributions (§731/§732/§737) ---
    TechnicalAuthority(
        citation="IRC §731(a)",
        authority_type="statute",
        title="Partnership Distributions — Nonrecognition General Rule",
        year=1954,
        relevance="No gain recognized on distribution except to extent money exceeds outside basis",
        key_holding="In the case of a distribution by a partnership to a partner: (1) gain is recognized only to the extent money distributed exceeds the partner's basis in the partnership interest (outside basis), (2) loss is recognized only on a liquidating distribution of solely money, unrealized receivables, and inventory. Gain is capital gain.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["731", "distribution", "nonrecognition", "outside basis", "partnership"],
    ),
    TechnicalAuthority(
        citation="IRC §737(a)",
        authority_type="statute",
        title="§737 — Recognition of Pre-Contribution Gain on Distribution",
        year=1992,
        relevance="Distribution of property to contributing partner triggers gain on previously contributed property",
        key_holding="If property (other than money) is distributed to a partner who contributed appreciated property within 7 years, the contributing partner recognizes gain equal to the lesser of: (1) the excess of the FMV of distributed property over outside basis, or (2) the net pre-contribution gain (remaining §704(c) built-in gain on contributed property still held by the partnership).",
        taxpayer_favorable=False,
        weight="primary",
        topics=["737", "pre-contribution gain", "distribution", "7-year rule"],
    ),

    # --- Hot Assets (§751) ---
    TechnicalAuthority(
        citation="IRC §751(a)",
        authority_type="statute",
        title="§751 — Unrealized Receivables and Inventory Items (Hot Assets)",
        year=1954,
        relevance="Sale or exchange of partnership interest: gain attributable to hot assets is ordinary income",
        key_holding="The amount of money or FMV of property received by a transferor partner in exchange for all or part of the partner's interest in the partnership attributable to unrealized receivables or inventory items (hot assets) is considered as received in exchange for property other than a capital asset — resulting in ordinary income (not capital gain).",
        facts_summary="Hot assets include: (1) unrealized receivables (including §1245/§1250 recapture), and (2) inventory items (including property that would not be capital asset or §1231 property if sold by partnership). §751(b) applies similar rules to certain disproportionate distributions.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["751", "hot assets", "unrealized receivables", "inventory", "ordinary income"],
    ),

    # --- §754 Election / §743(b) Basis Adjustment ---
    TechnicalAuthority(
        citation="IRC §754",
        authority_type="statute",
        title="§754 Election — Optional Adjustment to Basis",
        year=1954,
        relevance="Election to adjust inside basis of partnership assets upon transfer or distribution",
        key_holding="If a partnership files an election under §754, the basis of partnership property shall be adjusted under §743(b) (in the case of a transfer of a partnership interest) or §734(b) (in the case of a distribution of partnership property). Once made, the election applies to all subsequent transfers and distributions unless revoked with IRS consent.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["754", "election", "basis adjustment", "transfer", "distribution"],
    ),
    TechnicalAuthority(
        citation="IRC §743(b)",
        authority_type="statute",
        title="§743(b) — Basis Adjustment on Transfer of Interest",
        year=1954,
        relevance="If §754 election in effect, inside basis adjusted to reflect purchase price paid for interest",
        key_holding="If a §754 election is in effect, when a partnership interest is transferred by sale/exchange or upon death, the partnership adjusts the basis of its assets with respect to the transferee partner by the difference between the transferee's outside basis and the transferee's share of the partnership's inside basis (common basis). Positive adjustment: step-up. Negative adjustment: step-down.",
        facts_summary="Mandatory §743(b) adjustment: §743(d) requires a basis adjustment (even without §754 election) if the partnership has a substantial built-in loss (inside basis exceeds FMV of partnership assets by more than $250,000).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["743(b)", "basis adjustment", "step-up", "754 election", "transferee partner"],
    ),
    TechnicalAuthority(
        citation="IRC §734(b)",
        authority_type="statute",
        title="§734(b) — Basis Adjustment on Distribution",
        year=1954,
        relevance="If §754 election in effect, partnership adjusts inside basis following distribution",
        key_holding="If a §754 election is in effect, the partnership adjusts the basis of its remaining assets following a distribution by: (1) increasing basis by gain recognized to distributee partner plus excess of pre-distribution inside basis over distributee's basis in distributed property, or (2) decreasing basis by loss recognized to distributee plus excess of distributee's basis in distributed property over pre-distribution inside basis.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["734(b)", "basis adjustment", "distribution", "754 election"],
    ),

    # --- Partnership-Level Audit Rules ---
    TechnicalAuthority(
        citation="IRC §6221(a)",
        authority_type="statute",
        title="BBA — Centralized Partnership Audit Regime",
        year=2015,
        relevance="Partnership-level audit and adjustment regime (Bipartisan Budget Act of 2015)",
        key_holding="Any adjustment to items of income, gain, loss, deduction, or credit of a partnership shall be determined, and any tax attributable thereto shall be assessed and collected, at the partnership level. The partnership pays an 'imputed underpayment' unless it elects to push out adjustments to partners under §6226. Effective for tax years beginning after 12/31/2017.",
        facts_summary="Partnership must designate a partnership representative (replaces TMP). Small partnerships (100 or fewer eligible partners) may elect out under §6221(b). Push-out election under §6226 shifts liability to reviewed-year partners.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["BBA", "centralized audit", "imputed underpayment", "partnership representative"],
    ),

    # --- Key Regulations ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.704-2",
        authority_type="regulation",
        title="§704(b) — Nonrecourse Deductions and Minimum Gain",
        year=1991,
        relevance="Rules for allocating partnership nonrecourse deductions and minimum gain chargebacks",
        key_holding="Nonrecourse deductions must be allocated in accordance with how partner interests in minimum gain are allocated. When partnership minimum gain decreases (e.g., debt repaid or property value increases), each partner must be allocated income/gain equal to their share of the net decrease — the 'minimum gain chargeback.' Partner nonrecourse debt follows similar rules under §1.704-2(i).",
        facts_summary="Partnership minimum gain = excess of nonrecourse debt over book basis of property securing the debt. These rules ensure that tax benefits from nonrecourse-financed deductions are eventually recaptured through income allocations.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["704(b)", "nonrecourse deductions", "minimum gain", "minimum gain chargeback"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.752-1 through -3",
        authority_type="regulation",
        title="§752 — Partner's Share of Partnership Liabilities",
        year=1991,
        relevance="Rules for allocating partnership liabilities among partners (affects outside basis)",
        key_holding="Recourse liabilities: allocated to the partner who bears the economic risk of loss (constructive liquidation analysis under §1.752-2). Nonrecourse liabilities: allocated in 3 tiers — (1) minimum gain, (2) §704(c) minimum gain, (3) based on profits interests (or other significant item method). Increase in partner's share = deemed cash contribution (increases outside basis). Decrease = deemed cash distribution.",
        facts_summary="The economic risk of loss analysis under §1.752-2 uses a 'constructive liquidation' scenario — all assets worthless, all liabilities due, who ultimately pays? Bottom-dollar payment obligations and certain guarantees may be disregarded under anti-abuse rules (2019 final regs).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["752", "liabilities", "recourse", "nonrecourse", "outside basis", "economic risk of loss"],
    ),

    # --- Case Law ---
    TechnicalAuthority(
        citation="Canal Corp. v. Commissioner, 135 T.C. 199 (2010)",
        authority_type="case_law",
        title="Canal Corp. — Disguised Sale of Partnership Interest",
        year=2010,
        relevance="IRS successfully recharacterized leveraged partnership transaction as disguised sale",
        key_holding="Tax Court held that a complex leveraged partnership transaction (contribution of property followed by debt-financed distribution) was a disguised sale under §707(a)(2)(B). The court looked at the economic substance of the overall transaction, including the use of partnership debt to fund distributions to the contributing partner.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["707", "disguised sale", "leveraged partnership", "economic substance"],
    ),
]
