"""Technical authorities for international tax provisions.

Covers §951A GILTI, §250 FDII, §904 FTC limitation, §367 outbound
transfers, Subpart F income, PFIC rules, and related international
tax provisions enacted or modified by TCJA.
"""

from .base import TechnicalAuthority

INTERNATIONAL_TAX_AUTHORITIES = [
    # --- GILTI (§951A) ---
    TechnicalAuthority(
        citation="IRC §951A(a)",
        authority_type="statute",
        title="GILTI — Global Intangible Low-Taxed Income Inclusion",
        year=2017,
        relevance="U.S. shareholders of CFCs must include GILTI in gross income currently",
        key_holding="Each U.S. shareholder of a CFC must include in gross income its GILTI amount for the taxable year. GILTI = net CFC tested income − net deemed tangible income return (10% of QBAI less certain interest expense). Applies to tax years of foreign corporations beginning after 12/31/2017.",
        facts_summary="GILTI operates as a minimum tax on CFC earnings exceeding a 10% return on tangible assets (QBAI). Effectively targets 'excess' returns attributable to intangible assets held offshore.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["GILTI", "951A", "CFC", "QBAI", "international", "TCJA"],
    ),
    TechnicalAuthority(
        citation="IRC §951A(d)",
        authority_type="statute",
        title="GILTI — Qualified Business Asset Investment (QBAI)",
        year=2017,
        relevance="QBAI = average aggregate adjusted bases of specified tangible property used in CFC's trade or business",
        key_holding="QBAI is the average of the aggregate adjusted bases (determined under §168 as if placed in service in the U.S.) of specified tangible property used in the production of tested income. Higher QBAI reduces GILTI inclusion by increasing the deemed tangible income return (10% of QBAI).",
        facts_summary="Creates incentive to hold tangible assets offshore. Basis determined using U.S. depreciation rules (ADS straight-line). Anti-abuse rules prevent artificial inflation of QBAI.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["GILTI", "QBAI", "tangible property", "CFC", "adjusted basis"],
    ),
    TechnicalAuthority(
        citation="IRC §250(a)(1)(B)",
        authority_type="statute",
        title="§250 GILTI Deduction — 50% (37.5% after 2025)",
        year=2017,
        relevance="C corporations may deduct 50% of GILTI inclusion, resulting in effective 10.5% rate",
        key_holding="A C corporation is allowed a deduction equal to 50% of its GILTI inclusion (plus §78 gross-up). This effectively reduces the corporate tax rate on GILTI from 21% to 10.5%. The deduction decreases to 37.5% for tax years beginning after 12/31/2025 (effective rate increases to 13.125%).",
        facts_summary="Only available to C corporations, not individuals (unless §962 election made). Combined with §960 FTC for foreign taxes on GILTI, can reduce or eliminate residual U.S. tax.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["250", "GILTI deduction", "50%", "10.5%", "C corporation"],
    ),

    # --- FDII (§250) ---
    TechnicalAuthority(
        citation="IRC §250(a)(1)(A)",
        authority_type="statute",
        title="FDII — Foreign-Derived Intangible Income Deduction",
        year=2017,
        relevance="37.5% deduction for FDII, resulting in effective 13.125% rate on export income",
        key_holding="A C corporation is allowed a deduction equal to 37.5% of its FDII. This results in an effective tax rate of 13.125% on FDII (vs. 21% on domestic income). FDII deduction decreases to 21.875% for tax years beginning after 12/31/2025 (effective rate: 16.406%).",
        facts_summary="FDII = deemed intangible income × (foreign-derived deduction eligible income / deduction eligible income). Requires substantiation that income is derived from serving foreign markets (property sold for foreign use, services provided to foreign persons).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["FDII", "250", "foreign-derived", "13.125%", "export incentive"],
    ),
    TechnicalAuthority(
        citation="IRC §250(b)",
        authority_type="statute",
        title="FDII — Computation and Definitions",
        year=2017,
        relevance="FDII formula: deemed intangible income × foreign-derived ratio",
        key_holding="FDII = deemed intangible income (DEI − 10% of QBAI) × (foreign-derived DEI / total DEI). DEI = gross income less allocable deductions, excluding certain categories (Subpart F, GILTI, CFC dividends, financial services income, domestic oil/gas income). QBAI is the same tangible asset base used for GILTI.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["FDII", "250", "DEI", "deemed intangible income", "QBAI"],
    ),

    # --- FTC (§901/§904) ---
    TechnicalAuthority(
        citation="IRC §901(a)",
        authority_type="statute",
        title="Foreign Tax Credit — General Rule",
        year=1918,
        relevance="Credit against U.S. tax for foreign income taxes paid or accrued",
        key_holding="A taxpayer may choose to claim a credit against U.S. tax for the amount of any income, war profits, and excess profits taxes paid or accrued during the taxable year to any foreign country or U.S. possession. Alternative: deduction under §164.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["FTC", "901", "foreign tax credit", "creditable taxes"],
    ),
    TechnicalAuthority(
        citation="IRC §904(a)",
        authority_type="statute",
        title="FTC Limitation — Overall Limitation Formula",
        year=1986,
        relevance="FTC limited to U.S. tax × (foreign source taxable income / worldwide taxable income)",
        key_holding="The total FTC shall not exceed the amount of U.S. tax multiplied by the ratio of foreign source taxable income to worldwide taxable income. This prevents foreign taxes from offsetting U.S. tax on U.S.-source income.",
        facts_summary="Separate limitation applies to each 'basket' or category of income under §904(d). Excess credits can be carried back 1 year and forward 10 years under §904(c).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["FTC", "904", "limitation", "foreign source income", "basket"],
    ),
    TechnicalAuthority(
        citation="IRC §904(d)",
        authority_type="statute",
        title="FTC — Separate Limitation Categories (Baskets)",
        year=2017,
        relevance="Separate FTC baskets: general, passive, GILTI, foreign branch",
        key_holding="Post-TCJA FTC baskets: (1) passive category income, (2) general category income, (3) foreign branch income (new post-TCJA), (4) GILTI (§951A). Each category has its own FTC limitation computed under §904(a). Cross-crediting between baskets is not permitted.",
        facts_summary="GILTI basket FTC is computed separately under §960(d) and limited to 80% of foreign taxes deemed paid. No carryback/carryforward for GILTI FTC.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["FTC", "904(d)", "baskets", "passive", "general", "GILTI", "foreign branch"],
    ),
    TechnicalAuthority(
        citation="IRC §960(a)",
        authority_type="statute",
        title="Deemed Paid FTC — Subpart F and GILTI",
        year=2017,
        relevance="Corporate shareholders deemed to have paid proportionate share of CFC's foreign taxes",
        key_holding="If a domestic corporation includes amounts in gross income under §951(a) (Subpart F) or §951A (GILTI), it shall be deemed to have paid so much of such foreign corporation's foreign income taxes as are properly attributable to such items of income. Post-TCJA: credit computed on a current-year basis (no pooling).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["960", "deemed paid", "FTC", "CFC", "Subpart F", "GILTI"],
    ),

    # --- Subpart F ---
    TechnicalAuthority(
        citation="IRC §951(a)",
        authority_type="statute",
        title="Subpart F Income — Current Inclusion",
        year=1962,
        relevance="U.S. shareholders of CFCs must include Subpart F income currently",
        key_holding="Every U.S. shareholder of a CFC must include in gross income: (1) the shareholder's pro rata share of Subpart F income, and (2) the shareholder's pro rata share of any increase in earnings invested in U.S. property (§956). Inclusion is required regardless of actual distributions.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["Subpart F", "951", "CFC", "current inclusion", "U.S. shareholder"],
    ),
    TechnicalAuthority(
        citation="IRC §952(a)",
        authority_type="statute",
        title="Subpart F Income — Definition",
        year=1962,
        relevance="Defines categories of Subpart F income (FPHCI, FBC sales/services income, etc.)",
        key_holding="Subpart F income includes: (1) insurance income (§953), (2) foreign base company income (§954) — including foreign personal holding company income (FPHCI: dividends, interest, rents, royalties, gains from property transactions), foreign base company sales income, and foreign base company services income, and (3) international boycott income.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["Subpart F", "952", "FPHCI", "foreign base company income"],
    ),

    # --- §367 Outbound Transfers ---
    TechnicalAuthority(
        citation="IRC §367(a)",
        authority_type="statute",
        title="§367(a) — Outbound Transfers to Foreign Corporations",
        year=1976,
        relevance="Gain recognized on transfer of appreciated property to foreign corporation unless exception applies",
        key_holding="If a U.S. person transfers property to a foreign corporation in an exchange described in §332, 351, 354, 356, or 361, the foreign corporation shall not be considered a corporation for purposes of determining the extent to which gain shall be recognized. Effect: gain is recognized on the transfer unless an exception applies.",
        facts_summary="Exceptions: active trade or business assets may qualify for non-recognition under Reg. §1.367(a)-3. Intangible property transfers are subject to mandatory deemed royalty treatment under §367(d). Outbound stock transfers: gain recognized unless §367(a)(2) exception (active trade or business) is met.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["367", "outbound transfer", "gain recognition", "foreign corporation"],
    ),
    TechnicalAuthority(
        citation="IRC §367(d)",
        authority_type="statute",
        title="§367(d) — Outbound Transfers of Intangibles",
        year=1984,
        relevance="Transfer of intangible property to foreign corporation treated as sale for contingent royalty payments",
        key_holding="If a U.S. person transfers intangible property (§936(h)(3)(B)) to a foreign corporation in a §351 or §361 exchange, the transferor is treated as having sold the intangible for annual payments contingent on the productivity, use, or disposition of the property. Amounts are included in income over the useful life of the intangible (or 20 years minimum post-TCJA).",
        taxpayer_favorable=False,
        weight="primary",
        topics=["367(d)", "intangible property", "deemed royalty", "outbound transfer"],
    ),

    # --- PFIC ---
    TechnicalAuthority(
        citation="IRC §1297(a)",
        authority_type="statute",
        title="PFIC — Passive Foreign Investment Company Definition",
        year=1986,
        relevance="Foreign corporation is PFIC if 75%+ of income is passive or 50%+ of assets produce passive income",
        key_holding="A foreign corporation is a PFIC if: (1) 75% or more of its gross income is passive income (income test), or (2) 50% or more of its assets (by value, or adjusted basis if elected) produce or are held for passive income (asset test). Once a PFIC, always a PFIC (unless purging election made).",
        facts_summary="U.S. shareholders of PFICs face harsh tax treatment under §1291 (excess distribution regime) unless a QEF election (§1293) or mark-to-market election (§1296) is made. PFIC rules apply regardless of ownership percentage.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["PFIC", "1297", "passive income", "foreign corporation", "75%", "50%"],
    ),

    # --- Key Regulations/Guidance ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.951A-1 through -5",
        authority_type="regulation",
        title="GILTI Final Regulations",
        year=2019,
        relevance="Comprehensive regulations implementing GILTI computation framework",
        key_holding="Final regulations provide rules for computing GILTI, including: tested income/loss, QBAI, specified interest expense, CFC-level determinations, and the interaction with §250 deduction. Adopts a 'tested unit' concept for allocating income and QBAI. Provides rules for domestic partnerships and their partners.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["GILTI", "951A", "regulations", "tested income", "QBAI", "tested unit"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.250(b)-1 through -6",
        authority_type="regulation",
        title="FDII Final Regulations",
        year=2020,
        relevance="Detailed rules for determining FDII including documentation requirements",
        key_holding="Regulations provide rules for determining FDDEI (foreign-derived deduction eligible income), including: substantiation that property is for foreign use (documentation of ultimate destination), services provided to persons or with respect to property located outside the U.S. Provides specific rules for digital transactions, IP licenses, and mixed transactions.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["FDII", "250", "regulations", "FDDEI", "documentation", "foreign use"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.861-8",
        authority_type="regulation",
        title="Expense Allocation and Apportionment — Source Rules",
        year=1977,
        relevance="Rules for allocating and apportioning deductions between U.S. and foreign source income",
        key_holding="Deductions are first allocated to a class of gross income (based on factual relationship) and then apportioned between U.S. and foreign source income (and among FTC baskets). Interest expense: asset-based apportionment under §1.861-9. R&D expense: apportioned based on sales or gross income. Stewardship expenses: allocated to related income. SG&A: apportioned based on various methods.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["861", "expense allocation", "apportionment", "source rules", "FTC"],
    ),
]
