"""Technical authorities for the Corporate Alternative Minimum Tax (CAMT).

Covers §55 (as amended by IRA 2022), §56A AFSI adjustments, §59(k)
applicable corporation determination, and related guidance.
"""

from .base import TechnicalAuthority

CAMT_AUTHORITIES = [
    TechnicalAuthority(
        citation="IRC §55(a) (as amended by IRA 2022)",
        authority_type="statute",
        title="Corporate AMT — General Rule",
        year=2022,
        relevance="CAMT equals excess of tentative minimum tax (15% AFSI) over regular tax + BEAT",
        key_holding="There is imposed a tax equal to the excess (if any) of the tentative minimum tax for the taxable year over the sum of the regular tax for the taxable year plus the base erosion minimum tax amount. For applicable corporations, the tentative minimum tax is 15% of AFSI.",
        facts_summary="Effective for tax years beginning after 12/31/2022. Replaces the pre-TCJA corporate AMT. Only applies to 'applicable corporations' with ≥$1B average AFSI.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["CAMT", "55", "minimum tax", "15%", "AFSI"],
    ),
    TechnicalAuthority(
        citation="IRC §56A(a)",
        authority_type="statute",
        title="Adjusted Financial Statement Income (AFSI) — Definition",
        year=2022,
        relevance="AFSI = net income/loss on applicable financial statement + adjustments",
        key_holding="AFSI is the net income or loss on the taxpayer's applicable financial statement (AFS), adjusted as provided in §56A. The AFS is generally the financial statement filed with the SEC (10-K); if none, GAAP statements audited by a CPA; if none, filed with a government agency.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["CAMT", "AFSI", "56A", "financial statement", "AFS"],
    ),
    TechnicalAuthority(
        citation="IRC §56A(c)(2)",
        authority_type="statute",
        title="AFSI Adjustment — Federal Income Tax",
        year=2022,
        relevance="Federal income tax expense excluded from AFSI",
        key_holding="AFSI does not include federal income tax expense (or benefit) reported on the financial statements. Both current and deferred federal income tax must be excluded.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["CAMT", "AFSI adjustment", "income tax expense"],
    ),
    TechnicalAuthority(
        citation="IRC §56A(c)(13)",
        authority_type="statute",
        title="AFSI Adjustment — Depreciation",
        year=2022,
        relevance="Use tax depreciation instead of book depreciation for AFSI",
        key_holding="For property for which a deduction is allowable under §167, AFSI is determined by substituting the deduction allowable under §167 (tax depreciation) for the depreciation expense used in determining the financial statement net income.",
        facts_summary="This is the most significant AFSI adjustment for capital-intensive companies. Allows use of MACRS, bonus depreciation, and §179 in AFSI computation.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["CAMT", "depreciation", "AFSI adjustment", "MACRS", "bonus depreciation"],
    ),
    TechnicalAuthority(
        citation="IRC §56A(c)(11)",
        authority_type="statute",
        title="AFSI Adjustment — Defined Benefit Pension Plans",
        year=2022,
        relevance="AFSI uses deductible pension contributions instead of book pension expense",
        key_holding="For defined benefit pension plans, AFSI is adjusted to replace book pension expense with the amount deductible under §404.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["CAMT", "pension", "AFSI adjustment", "defined benefit"],
    ),
    TechnicalAuthority(
        citation="IRC §59(k)",
        authority_type="statute",
        title="Applicable Corporation — Definition",
        year=2022,
        relevance="$1B average AFSI threshold for CAMT applicability",
        key_holding="An applicable corporation is any corporation (other than S corp, RIC, or REIT) which meets the average annual AFSI test. The test is met if the average annual AFSI for the 3-taxable-year period ending with the prior taxable year exceeds $1,000,000,000. Aggregation rules apply for controlled groups.",
        facts_summary="Once a corporation becomes an applicable corporation, it remains one until AFSI falls below $1B for a specified period. Foreign-parented groups: $100M US AFSI threshold in addition to $1B worldwide.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["CAMT", "applicable corporation", "59(k)", "$1B threshold"],
    ),
    TechnicalAuthority(
        citation="IRC §59(l)",
        authority_type="statute",
        title="CAMT Foreign Tax Credit",
        year=2022,
        relevance="Separate FTC computation for CAMT purposes",
        key_holding="An applicable corporation is allowed a credit against CAMT for foreign income taxes paid or accrued by the corporation. Computed separately from the regular FTC under §901/§960. The CAMT FTC limitation is based on the ratio of foreign-source AFSI to total AFSI.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["CAMT", "foreign tax credit", "59(l)"],
    ),
    TechnicalAuthority(
        citation="IRC §53(e)",
        authority_type="statute",
        title="CAMT Credit — Carryforward",
        year=2022,
        relevance="CAMT paid generates credit usable against regular tax in future years",
        key_holding="Any CAMT paid generates a minimum tax credit that can be carried forward indefinitely and used to offset regular tax liability in future years (to the extent regular tax exceeds tentative minimum tax).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["CAMT", "minimum tax credit", "carryforward", "53(e)"],
    ),

    # --- Treasury / IRS Guidance ---
    TechnicalAuthority(
        citation="Notice 2023-7",
        authority_type="notice",
        title="Initial CAMT Guidance — Applicable Corporation Determination",
        year=2023,
        relevance="Interim guidance on determining applicable corporation status",
        key_holding="Provides initial guidance on computing average AFSI for the $1B threshold, including rules for short taxable years, predecessor corporations, and aggregation of controlled group members. Safe harbor for determining AFS for private companies.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["CAMT", "applicable corporation", "aggregation", "safe harbor"],
    ),
    TechnicalAuthority(
        citation="Notice 2023-64",
        authority_type="notice",
        title="CAMT Guidance — AFSI Adjustments",
        year=2023,
        relevance="Detailed guidance on computing AFSI adjustments",
        key_holding="Provides guidance on the depreciation adjustment (§56A(c)(13)), pension adjustment, and certain other AFSI modifications. Addresses treatment of tax consolidation vs. financial statement consolidation differences.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["CAMT", "AFSI", "depreciation", "pension", "adjustments"],
    ),
    TechnicalAuthority(
        citation="Prop. Reg. §1.56A-1 through §1.56A-21 (REG-112129-23)",
        authority_type="regulation",
        title="Proposed CAMT Regulations",
        year=2024,
        relevance="Comprehensive proposed regulations for CAMT computation",
        key_holding="Proposed regulations providing detailed rules for: determining applicable corporation status, computing AFSI (including all §56A adjustments), treatment of consolidated groups, partnerships, foreign corporations, and the CAMT FTC. Anticipated effective date: tax years ending after final regulations published.",
        facts_summary="Over 600 pages of proposed regulations. Key areas: depreciation adjustment mechanics, stock compensation, partnership AFSI allocation, consolidated group rules, and international provisions.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["CAMT", "proposed regulations", "AFSI", "consolidated groups"],
    ),
    TechnicalAuthority(
        citation="Notice 2024-10",
        authority_type="notice",
        title="CAMT — Penalty Relief and Transition Rules",
        year=2024,
        relevance="Penalty relief for CAMT estimated tax payments during transition",
        key_holding="Provides penalty relief for underpayment of estimated tax attributable to CAMT for the first three taxable years. Taxpayers will not be subject to penalties for failure to include CAMT in estimated tax payments if certain conditions are met.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["CAMT", "penalties", "estimated tax", "transition"],
    ),
]
