"""Technical authority database for accounting methods.

Covers §446 overall method of accounting, §481(a) adjustments, Form 3115
procedures, cash vs. accrual method elections, and change-in-method rules.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from revenue_recognition.technical_authority.authorities.base import (
    TechnicalAuthority, AuthorityLookup,
)

ACCOUNTING_METHOD_AUTHORITIES = [
    # --- Core Statutes ---
    TechnicalAuthority(
        citation="IRC §446(a)",
        authority_type="statute",
        title="General Rule — Method of Accounting",
        year=1986,
        relevance="Taxable income computed under method regularly used by taxpayer",
        key_holding="Taxable income shall be computed under the method of accounting on the basis of which the taxpayer regularly computes his income in keeping his books.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["accounting method", "446", "book conformity"],
    ),
    TechnicalAuthority(
        citation="IRC §446(b)",
        authority_type="statute",
        title="Exceptions — Method Must Clearly Reflect Income",
        year=1986,
        relevance="IRS may require method change if method does not clearly reflect income",
        key_holding="If no method of accounting has been regularly used by the taxpayer, or if the method used does not clearly reflect income, the computation of taxable income shall be made under such method as, in the opinion of the Secretary, does clearly reflect income.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["accounting method", "clearly reflect income", "IRS authority"],
    ),
    TechnicalAuthority(
        citation="IRC §446(c)",
        authority_type="statute",
        title="Permissible Methods",
        year=1986,
        relevance="List of permissible accounting methods: cash, accrual, special methods",
        key_holding="Permissible methods include: (1) cash receipts and disbursements, (2) accrual method, (3) any other method permitted by the Code, or (4) any combination of the foregoing permitted by regulations.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["accounting method", "cash method", "accrual method"],
    ),
    TechnicalAuthority(
        citation="IRC §446(e)",
        authority_type="statute",
        title="IRS Consent Required for Method Changes",
        year=1986,
        relevance="Method changes require IRS consent (Form 3115)",
        key_holding="A taxpayer who changes the method of accounting on the basis of which he regularly computes his income in keeping his books shall, before computing his taxable income under the new method, secure the consent of the Secretary.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["method change", "446(e)", "IRS consent", "Form 3115"],
    ),
    TechnicalAuthority(
        citation="IRC §448(a)",
        authority_type="statute",
        title="Limitation on Use of Cash Method",
        year=1986,
        relevance="C corporations, partnerships with C corp partners, and tax shelters generally cannot use cash method",
        key_holding="C corporations, partnerships with C corporation partners, and tax shelters are required to use the accrual method. Exceptions for small businesses meeting the §448(c) gross receipts test ($29M for 2024, inflation-adjusted).",
        taxpayer_favorable=False,
        weight="primary",
        topics=["cash method", "448", "accrual method required", "gross receipts test"],
    ),
    TechnicalAuthority(
        citation="IRC §448(c)",
        authority_type="statute",
        title="Small Business Gross Receipts Test",
        year=2017,
        relevance="$29M (2024) average gross receipts threshold for cash method eligibility",
        key_holding="A corporation or partnership meets the gross receipts test if average annual gross receipts for the 3-taxable-year period ending with the prior taxable year does not exceed the inflation-adjusted threshold ($29M for 2024).",
        facts_summary="TCJA significantly expanded small business eligibility by raising the threshold from $5M to $25M (now $29M inflation-adjusted). Also applies to §263A, §460, §471 exceptions.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["gross receipts test", "448(c)", "small business", "cash method"],
    ),

    # --- §481(a) Adjustment ---
    TechnicalAuthority(
        citation="IRC §481(a)",
        authority_type="statute",
        title="§481(a) Adjustment for Method Changes",
        year=1986,
        relevance="Adjustments required to prevent duplication or omission of income/deductions",
        key_holding="In computing taxable income for any taxable year, if the taxpayer's method of accounting is changed, adjustments shall be made to prevent amounts from being duplicated or omitted solely by reason of such change.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["481(a)", "method change", "adjustment", "spread period"],
    ),
    TechnicalAuthority(
        citation="IRC §481(b)",
        authority_type="statute",
        title="§481(b) Limitation on Tax",
        year=1986,
        relevance="Cap on tax attributable to §481(a) adjustments in certain involuntary changes",
        key_holding="If the §481(a) adjustment is attributable to an involuntary change initiated by the IRS, the increase in tax cannot exceed the net §481(a) adjustment allocable to 1 taxable year under a 3-year allocation.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["481(b)", "tax limitation", "involuntary change"],
    ),

    # --- Treasury Regulations ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.446-1(e)(2)",
        authority_type="regulation",
        title="Method Change Procedures",
        year=1992,
        relevance="Detailed rules for obtaining consent to change accounting method",
        key_holding="A taxpayer must file Form 3115, Application for Change in Accounting Method, to obtain consent. Automatic consent procedures are available for certain changes under the applicable revenue procedure.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["method change", "Form 3115", "automatic consent", "procedures"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.446-1(e)(2)(ii)(a)",
        authority_type="regulation",
        title="Definition of 'Method of Accounting'",
        year=1992,
        relevance="What constitutes a method of accounting vs. a correction of error",
        key_holding="A method of accounting includes not only the overall method but also the accounting treatment of any item. A change in method involves a change in the treatment of a material item. A change that is not a change in method is a correction of an error (no Form 3115 needed).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["method of accounting", "definition", "material item", "error correction"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.481-1(a)",
        authority_type="regulation",
        title="§481(a) Adjustment Computation",
        year=1992,
        relevance="How to compute the §481(a) adjustment",
        key_holding="The §481(a) adjustment is the difference between the item as reported under the old method and as it would have been reported under the new method for all open and closed years. Positive adjustments (income) are spread over 4 years; negative adjustments (deductions) are taken entirely in the year of change.",
        facts_summary="Key: 4-year spread for positive adjustments, 1-year for negative. If change is involuntary (IRS-initiated), different rules may apply.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["481(a)", "computation", "4-year spread", "adjustment"],
    ),

    # --- Revenue Procedures ---
    TechnicalAuthority(
        citation="Rev. Proc. 2015-13, 2015-5 I.R.B. 419",
        authority_type="rev_proc",
        title="General Procedures for Automatic Consent Method Changes",
        year=2015,
        relevance="Master procedural revenue procedure for automatic consent changes",
        key_holding="Establishes the general procedures for obtaining automatic consent to change an accounting method. Taxpayers file Form 3115 with their timely filed (including extensions) original return. Provides rules for duplicate filing, 5-year eligibility window, audit protection, and §481(a) adjustment period.",
        facts_summary="Still the governing procedural rev proc. Key: automatic consent changes get audit protection for prior years. 4-year spread for positive §481(a), 1 year for negative.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["automatic consent", "Rev. Proc. 2015-13", "Form 3115", "audit protection"],
    ),
    TechnicalAuthority(
        citation="Rev. Proc. 2024-23, 2024-22 I.R.B. 1",
        authority_type="rev_proc",
        title="List of Automatic Accounting Method Changes (Current Year)",
        year=2024,
        relevance="Current comprehensive list of changes eligible for automatic consent",
        key_holding="Provides the current comprehensive list of accounting method changes eligible for automatic IRS consent under Rev. Proc. 2015-13. Each designated change has a specific change number and applicable rules. Key sections include: overall method changes, timing rules, inventory, depreciation, and entity-specific items.",
        facts_summary="Supersedes Rev. Proc. 2022-14. Adds new automatic changes and modifies existing ones. The 'CAM list' practitioners reference for all automatic method changes.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["automatic consent", "Rev. Proc. 2024-23", "CAM list", "method change"],
    ),
    TechnicalAuthority(
        citation="Rev. Proc. 2015-14 (as modified)",
        authority_type="rev_proc",
        title="Non-Automatic Consent Procedures",
        year=2015,
        relevance="Procedures for method changes not on the automatic consent list",
        key_holding="Taxpayers requesting non-automatic consent to change a method of accounting must file Form 3115 during the year of change. The IRS National Office will review and issue a ruling letter. User fee required ($12,600 for 2024).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["non-automatic consent", "advance consent", "Form 3115", "user fee"],
    ),

    # --- Case Law ---
    TechnicalAuthority(
        citation="Commissioner v. South Texas Lumber Co., 333 U.S. 496 (1948)",
        authority_type="case_law",
        title="South Texas Lumber — IRS Authority Over Methods",
        year=1948,
        relevance="IRS has broad authority to require methods that clearly reflect income",
        key_holding="The Commissioner has broad discretion under §446(b) to determine whether a taxpayer's method of accounting clearly reflects income. Courts will not disturb the Commissioner's determination unless it is clearly unlawful.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["clearly reflect income", "IRS authority", "446(b)"],
    ),
    TechnicalAuthority(
        citation="Thor Power Tool Co. v. Commissioner, 439 U.S. 522 (1979)",
        authority_type="case_law",
        title="Thor Power Tool — Book/Tax Conformity Not Required",
        year=1979,
        relevance="Book and tax accounting methods need not conform",
        key_holding="Financial accounting and tax accounting serve different objectives. A method that is acceptable for financial reporting purposes (GAAP) is not necessarily acceptable for tax purposes. The 'clearly reflect income' standard operates independently of GAAP.",
        facts_summary="Taxpayer wrote down inventory to net realizable value for GAAP. IRS disallowed the write-down for tax purposes. Supreme Court upheld.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["clearly reflect income", "book-tax conformity", "GAAP vs tax"],
    ),
    TechnicalAuthority(
        citation="Graff Chevrolet Co. v. Campbell, 343 F.2d 568 (5th Cir. 1965)",
        authority_type="case_law",
        title="Graff Chevrolet — Voluntary Method Change",
        year=1965,
        relevance="Taxpayer cannot change method without IRS consent",
        key_holding="A taxpayer who has adopted a method of accounting cannot change to a different method without first obtaining IRS consent under §446(e). Unauthorized method changes are void.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["method change", "IRS consent", "unauthorized change"],
    ),
    TechnicalAuthority(
        citation="Advertisers Exchange, Inc. v. Commissioner, 25 T.C. 1086 (1956)",
        authority_type="case_law",
        title="Advertisers Exchange — Consistent Treatment Creates Method",
        year=1956,
        relevance="Consistent treatment of an item over 2+ years creates a method of accounting",
        key_holding="A taxpayer's consistent treatment of a material item over at least two consecutive taxable years constitutes an established method of accounting, which cannot be changed without IRS consent.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["method of accounting", "consistent treatment", "two-year rule"],
    ),
    TechnicalAuthority(
        citation="Wayne Bolt & Nut Co. v. Commissioner, T.C. Memo 1983-626",
        authority_type="case_law",
        title="Wayne Bolt — §481(a) Adjustment Protects Prior Years",
        year=1983,
        relevance="§481(a) adjustment provides audit protection for prior years",
        key_holding="The §481(a) adjustment mechanism ensures that the change in method captures all prior-year effects in a single computation, providing audit protection for prior-year positions that were treated under the old method.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["481(a)", "audit protection", "prior years"],
    ),

    # --- IRS Guidance ---
    TechnicalAuthority(
        citation="Rev. Rul. 90-38, 1990-1 C.B. 57",
        authority_type="rev_rul",
        title="What Constitutes a Change in Method of Accounting",
        year=1990,
        relevance="Distinguishes method change from error correction",
        key_holding="A change in the treatment of a material item used in at least two consecutive years is a change in method of accounting requiring Form 3115. Correction of a mathematical or posting error, or adjustment of a non-recurring item, is not a method change.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["method change", "error correction", "material item"],
    ),
    TechnicalAuthority(
        citation="CCA 201042023",
        authority_type="cca",
        title="Automatic vs. Non-Automatic Consent",
        year=2010,
        relevance="When a change qualifies for automatic consent vs. requiring advance consent",
        key_holding="A taxpayer must use the automatic consent procedures when the desired change is listed in the applicable revenue procedure. Using non-automatic procedures for a change listed as automatic will result in the request being returned.",
        taxpayer_favorable=True,
        weight="some",
        topics=["automatic consent", "non-automatic consent", "Form 3115"],
    ),
    TechnicalAuthority(
        citation="TAM 200627018",
        authority_type="tam",
        title="§481(a) Spread Period for Positive Adjustments",
        year=2006,
        relevance="4-year spread requirement for positive §481(a) adjustments",
        key_holding="A positive §481(a) adjustment (increasing taxable income) resulting from a voluntary method change is spread ratably over 4 taxable years beginning with the year of change. Acceleration occurs if the taxpayer ceases to engage in the trade or business.",
        taxpayer_favorable=True,
        weight="some",
        topics=["481(a)", "4-year spread", "positive adjustment"],
    ),
]


def get_accounting_methods_lookup() -> AuthorityLookup:
    """Return an AuthorityLookup loaded with accounting methods authorities."""
    return AuthorityLookup(list(ACCOUNTING_METHOD_AUTHORITIES))
