"""Technical authorities for compensation deduction rules.

Covers §162(a)(1) reasonable compensation, §162(m) executive compensation
limitation, §404(a)(5) deferred compensation timing, and related rules.
"""

from .base import TechnicalAuthority

COMPENSATION_AUTHORITIES = [
    # --- Primary Statutes ---
    TechnicalAuthority(
        citation="IRC §162(a)(1)",
        authority_type="statute",
        title="Reasonable Compensation Deduction",
        year=1986,
        relevance="General rule — reasonable compensation is deductible as ordinary and necessary business expense",
        key_holding="A deduction is allowed for a reasonable allowance for salaries or other compensation for personal services actually rendered.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["compensation", "reasonable compensation", "deduction"],
    ),
    TechnicalAuthority(
        citation="IRC §162(m)(1)",
        authority_type="statute",
        title="$1M Executive Compensation Limitation",
        year=1993,
        relevance="Core §162(m) — $1M cap on deduction for covered employee compensation",
        key_holding="No deduction shall be allowed for applicable employee remuneration with respect to any covered employee to the extent that the amount of such remuneration for the taxable year exceeds $1,000,000.",
        facts_summary="As amended by TCJA (2017) and ARPA (2021): applies to CEO, CFO, and three other highest-paid officers. Once a covered employee, always a covered employee (no grandfathering after 2027 for pre-TCJA arrangements).",
        taxpayer_favorable=False,
        weight="primary",
        topics=["162(m)", "covered employee", "executive compensation", "$1M limit"],
    ),
    TechnicalAuthority(
        citation="IRC §162(m)(3)",
        authority_type="statute",
        title="Covered Employee Definition",
        year=2017,
        relevance="Definition of covered employee — expanded by TCJA and ARPA",
        key_holding="Covered employee includes CEO, CFO, and three highest-compensated officers. Once an individual becomes a covered employee, they remain a covered employee for all future tax years (including after death or separation).",
        facts_summary="Post-TCJA: no performance-based compensation exception. ARPA (2021) expanded to include next 5 highest-compensated employees for companies with >$1B annual revenue.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["162(m)", "covered employee", "CEO", "CFO"],
    ),
    TechnicalAuthority(
        citation="IRC §404(a)(5)",
        authority_type="statute",
        title="Deferred Compensation — Timing of Deduction",
        year=1986,
        relevance="Deferred comp deduction timing — deductible when includible in employee income",
        key_holding="Contributions paid by an employer under a deferred compensation plan are deductible in the taxable year in which an amount attributable to the contribution is includible in the gross income of employees participating in the plan.",
        facts_summary="Applies to nonqualified deferred comp plans. Employer gets no deduction until employee includes in income (generally upon payment/distribution).",
        taxpayer_favorable=False,
        weight="primary",
        topics=["deferred compensation", "404(a)(5)", "timing", "nonqualified plan"],
    ),
    TechnicalAuthority(
        citation="IRC §409A",
        authority_type="statute",
        title="Nonqualified Deferred Compensation Rules",
        year=2004,
        relevance="§409A requirements for NQDC plans — penalties for violations",
        key_holding="Nonqualified deferred compensation must meet strict requirements regarding timing of deferral elections, distribution triggers, and acceleration prohibitions. Violations result in immediate income inclusion plus 20% penalty tax on the employee.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["deferred compensation", "409A", "NQDC", "penalties"],
    ),

    # --- Treasury Regulations ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.162-7(a)",
        authority_type="regulation",
        title="Reasonable Compensation — Factors",
        year=1960,
        relevance="Factors for determining reasonable compensation amount",
        key_holding="Whether compensation is reasonable is a question of fact. Relevant factors include the employee's qualifications, the nature and scope of work, the size and complexity of the business, comparable compensation in similar businesses, and the employer's compensation policy.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["reasonable compensation", "factors", "closely held"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.162-27(c)(2)",
        authority_type="regulation",
        title="§162(m) — Applicable Employee Remuneration",
        year=1995,
        relevance="What counts as applicable employee remuneration subject to the $1M cap",
        key_holding="Applicable employee remuneration includes all remuneration for services performed by a covered employee, whether or not the remuneration is paid directly by the publicly held corporation.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["162(m)", "remuneration", "compensation"],
    ),

    # --- Case Law ---
    TechnicalAuthority(
        citation="Exacto Spring Corp. v. Commissioner, 196 F.3d 833 (7th Cir. 1999)",
        authority_type="case_law",
        title="Exacto Spring — Independent Investor Test",
        year=1999,
        relevance="Reasonable compensation — independent investor test (7th Circuit)",
        key_holding="The test for reasonable compensation should be whether an independent investor would approve the compensation given the return on equity. If the company is earning a satisfactory return on equity after paying the compensation, it is presumptively reasonable.",
        facts_summary="Judge Posner's opinion established the independent investor test as the primary framework in the 7th Circuit for evaluating reasonable compensation.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["reasonable compensation", "independent investor test", "closely held"],
    ),
    TechnicalAuthority(
        citation="Menard, Inc. v. Commissioner, 560 F.3d 620 (7th Cir. 2009)",
        authority_type="case_law",
        title="Menard — Excessive Compensation",
        year=2009,
        relevance="Reasonable compensation — home improvement executive compensation found excessive",
        key_holding="$20M+ bonus to sole shareholder-CEO found unreasonable where comparable executives earned significantly less. Independent investor test applied.",
        facts_summary="John Menard received compensation exceeding $20M. Court found portion unreasonable, analyzing ROE and comparable CEO compensation.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["reasonable compensation", "excessive compensation", "independent investor test"],
    ),
    TechnicalAuthority(
        citation="Albertson's Inc. v. Commissioner, T.C. Memo 2015-3",
        authority_type="case_law",
        title="Albertson's — §162(m) Performance-Based Compensation",
        year=2015,
        relevance="§162(m) performance-based exception requirements (pre-TCJA)",
        key_holding="Compensation committee must have sole authority to establish and certify performance goals. Failure to properly establish outside director approval invalidates the performance-based exception.",
        facts_summary="Note: performance-based exception eliminated by TCJA for tax years after 12/31/2017 (with limited transition relief).",
        taxpayer_favorable=False,
        weight="some",
        topics=["162(m)", "performance-based compensation", "transition rule"],
    ),

    # --- IRS Guidance ---
    TechnicalAuthority(
        citation="Rev. Rul. 2007-12, 2007-1 C.B. 685",
        authority_type="rev_rul",
        title="Vacation Pay — All-Events Test",
        year=2007,
        relevance="Vacation pay accrual — vested vacation pay deductible when earned",
        key_holding="Vested vacation pay (i.e., vacation pay that is not forfeited on termination) satisfies the all-events test in the year the services are performed that give rise to the vacation pay liability, even if the amount is not determinable until year end.",
        facts_summary="Three situations analyzed. Vested vacation pay: deductible when earned. Forfeitable vacation pay: not deductible until vesting.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["vacation pay", "all-events test", "compensation", "vested"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 2008-29, 2008-1 C.B. 1149",
        authority_type="rev_rul",
        title="Bonus Accruals — Related Party 2½-Month Rule",
        year=2008,
        relevance="Bonus accruals to related parties — must be paid within 2½ months",
        key_holding="For accrual-method taxpayers, bonuses payable to employees who are related parties under §267 must be paid within 2½ months after year end to be deductible in the accrual year.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["bonus accrual", "related party", "compensation", "2.5 month rule"],
    ),
    TechnicalAuthority(
        citation="Notice 2018-68",
        authority_type="notice",
        title="Guidance on §162(m) After TCJA",
        year=2018,
        relevance="Post-TCJA guidance on covered employees and transition rules",
        key_holding="Provides interim guidance on identifying covered employees under amended §162(m). Addresses the elimination of the performance-based compensation exception and the transition rule for binding contracts in effect on 11/2/2017.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["162(m)", "TCJA", "covered employee", "transition rule"],
    ),
]
