"""Technical authorities for §461(h) economic performance rules.

Covers the three categories of liabilities (payment, service, property),
the all-events test, and special rules for contested liabilities, workers'
compensation, and tort liabilities.
"""

from .base import TechnicalAuthority

ECONOMIC_PERFORMANCE_AUTHORITIES = [
    # --- Primary Statutes ---
    TechnicalAuthority(
        citation="IRC §461(a)",
        authority_type="statute",
        title="General Rule for Taxable Year of Deduction",
        year=1986,
        relevance="General timing rule — deduction allowed in proper taxable year under method of accounting",
        key_holding="Amount shall be allowed as deduction for the taxable year that is the proper taxable year under the method of accounting used in computing taxable income.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["deduction timing", "accrual method", "all-events test"],
    ),
    TechnicalAuthority(
        citation="IRC §461(h)(1)",
        authority_type="statute",
        title="Economic Performance Requirement",
        year=1984,
        relevance="Core EP requirement — all-events test not met until economic performance occurs",
        key_holding="In determining whether an amount has been incurred, the all events test shall not be treated as met any earlier than when economic performance with respect to such item occurs.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["economic performance", "all-events test", "accrual method"],
    ),
    TechnicalAuthority(
        citation="IRC §461(h)(2)(A)(i)",
        authority_type="statute",
        title="EP for Services/Property Provided TO Taxpayer",
        year=1984,
        relevance="Service and property liabilities — EP when provided to taxpayer",
        key_holding="If the liability arises out of the providing of services or property to the taxpayer, economic performance occurs as such services or property is provided.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["economic performance", "service liability", "property liability"],
    ),
    TechnicalAuthority(
        citation="IRC §461(h)(2)(A)(ii)",
        authority_type="statute",
        title="EP for Services/Property Provided BY Taxpayer",
        year=1984,
        relevance="Taxpayer-provided services — EP as taxpayer provides services/property",
        key_holding="If the liability arises out of the providing of services or property by the taxpayer, economic performance occurs as the taxpayer provides such services or property.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["economic performance", "taxpayer services"],
    ),
    TechnicalAuthority(
        citation="IRC §461(h)(2)(B)",
        authority_type="statute",
        title="EP for Workers Compensation and Tort Liabilities",
        year=1984,
        relevance="Special EP rule — workers' comp and tort liabilities: EP when payments made",
        key_holding="If the liability requires a payment to another person and arises under any workers compensation act or out of any tort, economic performance occurs as the payments to such person are made.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["economic performance", "payment liability", "workers compensation", "tort liability"],
    ),
    TechnicalAuthority(
        citation="IRC §461(h)(2)(C)",
        authority_type="statute",
        title="EP for Other Payment Liabilities",
        year=1984,
        relevance="Payment liabilities — EP when payment is made",
        key_holding="If the liability requires the taxpayer to make a payment to another person and subparagraph (B) does not apply, economic performance occurs when payment is made.",
        facts_summary="Applies to taxes, insurance premiums, warranty claims, rebates, prizes, awards, and similar items where payment is the relevant economic activity.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["economic performance", "payment liability", "taxes", "insurance", "warranty"],
    ),

    # --- Treasury Regulations ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.461-1(a)(2)",
        authority_type="regulation",
        title="Accrual Method — General Rule",
        year=1957,
        relevance="All-events test: deduction when (1) all events have occurred establishing the fact of the liability, (2) amount can be determined with reasonable accuracy, and (3) economic performance has occurred",
        key_holding="Under an accrual method of accounting, a liability is incurred, and generally is taken into account for Federal income tax purposes, in the taxable year in which all the events have occurred that establish the fact of the liability, the amount can be determined with reasonable accuracy, and economic performance has occurred.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["all-events test", "accrual method", "reasonable accuracy"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.461-4(a)",
        authority_type="regulation",
        title="Economic Performance — General Rule",
        year=1992,
        relevance="Comprehensive EP regulations — rules for determining when EP occurs",
        key_holding="Except as otherwise provided, in the case of a liability of a taxpayer, economic performance occurs as provided in this section. A liability may not be taken into account under the recurring item exception before economic performance occurs.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["economic performance", "liability timing"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.461-4(d)(2)",
        authority_type="regulation",
        title="Services or Property Provided to Taxpayer",
        year=1992,
        relevance="EP for services/property provided to taxpayer — ratably as services provided",
        key_holding="If the liability of a taxpayer arises out of the providing of services or property to the taxpayer by another person, economic performance occurs as such person provides the services or property.",
        facts_summary="Example: if taxpayer enters into contract for consulting services, EP occurs as services are performed, regardless of when payment is made.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["economic performance", "service liability", "property liability", "ratably"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.461-4(g)(2)-(7)",
        authority_type="regulation",
        title="Payment Liabilities — Taxes, Insurance, Warranty, etc.",
        year=1992,
        relevance="Payment liabilities EP rules for specific categories",
        key_holding="For liabilities arising from taxes, insurance premiums, warranty/guarantee expenses, service contracts on property, rebates/refunds, awards/prizes, and jackpots — economic performance occurs as payment is made.",
        facts_summary="Covers the full list of payment liabilities. Each subsection addresses a specific category with the same result: EP upon payment.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["payment liability", "taxes", "insurance", "warranty", "rebates"],
    ),

    # --- Key Case Law ---
    TechnicalAuthority(
        citation="United States v. General Dynamics Corp., 481 U.S. 239 (1987)",
        authority_type="case_law",
        title="General Dynamics — All-Events Test for Self-Insurance",
        year=1987,
        relevance="All-events test — health care claims not fixed until filed",
        key_holding="The all-events test was not satisfied merely because employees had performed services giving rise to potential claims. The fact of liability was not established until claims were actually filed.",
        facts_summary="Defense contractor accrued self-insured health care costs when employees performed services. Supreme Court held liability not fixed until employees actually filed claims.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["all-events test", "self-insurance", "health care", "liability fixed"],
    ),
    TechnicalAuthority(
        citation="United States v. Hughes Properties, Inc., 476 U.S. 593 (1986)",
        authority_type="case_law",
        title="Hughes Properties — Progressive Slot Machine Jackpots",
        year=1986,
        relevance="All-events test — liability fixed when obligation becomes unconditional",
        key_holding="Casino could accrue deductions for progressive slot machine jackpots because state gaming regulations required payment, making the liability fixed even though the winner was unknown.",
        facts_summary="Casino accrued liabilities for amounts shown on progressive slot machines. Supreme Court held all-events test satisfied because Nevada law required eventual payment.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["all-events test", "liability fixed", "unconditional obligation"],
    ),
    TechnicalAuthority(
        citation="Washington Post Co. v. United States, 405 F.2d 1279 (Ct. Cl. 1969)",
        authority_type="case_law",
        title="Washington Post — Vacation Pay Accrual",
        year=1969,
        relevance="Vacation pay — all-events test timing",
        key_holding="Vacation pay could be accrued in the year earned by employees, even though not paid until the following year, as all events establishing the liability had occurred.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["vacation pay", "all-events test", "compensation", "accrual"],
    ),
    TechnicalAuthority(
        citation="IRC §461(f)",
        authority_type="statute",
        title="Contested Liabilities",
        year=1964,
        relevance="Contested liabilities — deduction when transferred to provide for satisfaction",
        key_holding="If a taxpayer contests an asserted liability and transfers money or property to provide for satisfaction of the asserted liability, the taxpayer may claim a deduction in the year of transfer.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["contested liability", "transfer", "deduction timing"],
    ),

    # --- IRS Guidance ---
    TechnicalAuthority(
        citation="Rev. Rul. 2007-3, 2007-1 C.B. 350",
        authority_type="rev_rul",
        title="Recurring Item Exception — Rebates",
        year=2007,
        relevance="Recurring item exception for trade rebate liabilities",
        key_holding="Trade rebates that are recurring in nature may qualify for the recurring item exception under §461(h)(3) if the all-events test (apart from EP) is met by year end and EP occurs within 8.5 months after year end.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["recurring item exception", "rebates", "economic performance"],
    ),
    TechnicalAuthority(
        citation="CCA 201446025",
        authority_type="cca",
        title="Economic Performance for Insurance Premiums",
        year=2014,
        relevance="Insurance premiums — payment liability timing",
        key_holding="Insurance premiums are payment liabilities under §461(h)(2)(C). Economic performance does not occur until the premiums are actually paid, regardless of when the coverage period begins.",
        taxpayer_favorable=False,
        weight="some",
        topics=["economic performance", "insurance", "payment liability"],
    ),
    TechnicalAuthority(
        citation="TAM 200043015",
        authority_type="tam",
        title="Warranty Accruals and Economic Performance",
        year=2000,
        relevance="Warranty reserve — payment liability EP",
        key_holding="Accrued warranty reserves do not satisfy economic performance until warranty claims are actually paid. Warranty obligations are payment liabilities under §461(h)(2)(C).",
        facts_summary="Taxpayer accrued warranty reserves based on historical claim experience. IRS held EP not met until actual warranty payments made.",
        taxpayer_favorable=False,
        weight="some",
        topics=["warranty", "payment liability", "economic performance", "reserves"],
    ),
]
