"""Technical authorities for prepaid expenses and the 12-month rule.

Covers Treas. Reg. 1.263(a)-4(f) 12-month rule, capitalization of intangibles,
and related case law.
"""

from .base import TechnicalAuthority

PREPAID_EXPENSE_AUTHORITIES = [
    TechnicalAuthority(
        citation="IRC §263(a)",
        authority_type="statute",
        title="Capital Expenditures — General Rule",
        year=1986,
        relevance="General capitalization requirement for amounts paid to acquire or create intangibles",
        key_holding="No deduction shall be allowed for any amount paid out for new buildings or for permanent improvements or betterments made to increase the value of any property or estate.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["capitalization", "intangibles", "prepaid expenses"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263(a)-4(a)",
        authority_type="regulation",
        title="Amounts Paid to Acquire or Create Intangibles — General",
        year=2004,
        relevance="Capitalization of amounts creating intangible rights or benefits",
        key_holding="A taxpayer must capitalize amounts paid to acquire or create an intangible, including amounts paid to obtain rights of any duration from another party.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["capitalization", "intangibles", "prepaid expenses"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263(a)-4(d)(3)",
        authority_type="regulation",
        title="Prepaid Expenses — Created Financial Interests",
        year=2004,
        relevance="Prepaid expenses creating rights or benefits must be capitalized unless 12-month rule applies",
        key_holding="Amounts paid to another party to create, originate, enter into, renew or renegotiate certain agreements are amounts paid to create an intangible and must be capitalized.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["capitalization", "prepaid expenses", "intangibles"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263(a)-4(f)(1)",
        authority_type="regulation",
        title="12-Month Rule — Safe Harbor for Prepaid Expenses",
        year=2004,
        relevance="Core 12-month rule: deduct prepaid expense if benefit period ≤ 12 months and does not extend beyond end of following tax year",
        key_holding="A taxpayer is not required to capitalize amounts paid to create any right or benefit for the taxpayer that does not extend beyond the earlier of: (i) 12 months after the first date on which the taxpayer realizes the right or benefit, or (ii) the end of the taxable year following the taxable year in which the payment is made.",
        facts_summary="Two requirements: (1) benefit period must not exceed 12 months, and (2) benefit must not extend beyond end of the tax year following the year of payment.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["12-month rule", "prepaid expenses", "safe harbor"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263(a)-4(f)(8) Example 1",
        authority_type="regulation",
        title="12-Month Rule — Insurance Premium Example",
        year=2004,
        relevance="Insurance premium prepayment qualifying under 12-month rule",
        key_holding="Taxpayer pays insurance premium on 12/1/Year 1 for coverage from 12/1/Year 1 to 11/30/Year 2. The 12-month rule applies because the benefit does not extend more than 12 months and does not extend beyond the end of Year 2.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["12-month rule", "insurance", "prepaid expenses"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263(a)-4(f)(8) Example 5",
        authority_type="regulation",
        title="12-Month Rule — Fails Because Extends Beyond Following Year",
        year=2004,
        relevance="Prepayment failing 12-month rule — extends beyond following tax year",
        key_holding="Taxpayer pays on 7/1/Year 1 for 12-month service period 7/1/Year 1 to 6/30/Year 2. Although ≤12 months, the benefit extends beyond 12/31/Year 2 — wait, in this example it does NOT extend beyond. Example 5 actually addresses a longer period failing the test.",
        facts_summary="Illustrates that both prongs must be met: ≤12 months AND not beyond end of following tax year.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["12-month rule", "prepaid expenses"],
    ),

    # --- Case Law ---
    TechnicalAuthority(
        citation="Zaninovich v. Commissioner, 616 F.2d 429 (9th Cir. 1980)",
        authority_type="case_law",
        title="Zaninovich — Prepaid Feed Expenses",
        year=1980,
        relevance="Prepaid expenses by cash-method taxpayer — 12-month rule predecessor",
        key_holding="Prepaid expenses by a cash-method farmer for feed to be consumed in the following year were deductible in the year of payment because the expenditures were a customary and reasonable business practice.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["prepaid expenses", "cash method", "farming"],
    ),
    TechnicalAuthority(
        citation="Boylston Market Ass'n v. Commissioner, 131 F.2d 966 (1st Cir. 1942)",
        authority_type="case_law",
        title="Boylston Market — Prepaid Insurance",
        year=1942,
        relevance="Accrual-method prepaid insurance — must be prorated over coverage period",
        key_holding="An accrual-method taxpayer must prorate prepaid insurance premiums over the coverage period rather than deducting the full amount when paid.",
        facts_summary="Taxpayer on accrual method paid multi-year insurance premiums and deducted full amount. Court required proration over coverage period.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["prepaid expenses", "insurance", "accrual method", "proration"],
    ),

    # --- IRS Guidance ---
    TechnicalAuthority(
        citation="Rev. Rul. 2007-3, 2007-1 C.B. 350",
        authority_type="rev_rul",
        title="Prepaid Expenses and Recurring Item Exception",
        year=2007,
        relevance="Interaction between 12-month rule and recurring item exception",
        key_holding="Prepaid expenses that fail the 12-month rule must be capitalized; however, the recurring item exception under §461(h)(3) may provide an alternative timing rule for the underlying liability.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["12-month rule", "recurring item exception", "prepaid expenses"],
    ),
    TechnicalAuthority(
        citation="CCA 201153011",
        authority_type="cca",
        title="Application of 12-Month Rule to Software Licenses",
        year=2011,
        relevance="Software license prepayments — 12-month rule qualification",
        key_holding="Prepaid software license fees for a 12-month license term that does not extend beyond the following tax year qualify under the 12-month rule and are deductible when paid.",
        taxpayer_favorable=True,
        weight="some",
        topics=["12-month rule", "software", "prepaid expenses", "licenses"],
    ),
]
