"""Capitalizable cost categories — specific expenses identified in rulings and cases.

Covers acquisition and procurement costs, taxes and government assessments,
environmental and legal costs, specific employee benefits, and unique
industry/production costs that must be capitalized under §263A and §471.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from revenue_recognition.technical_authority.authorities.base import TechnicalAuthority

CAPITALIZABLE_COSTS_AUTHORITIES = [
    # --- Acquisition and Procurement Costs ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-3(b)",
        authority_type="regulation",
        title="Inventory Cost — 'Necessary Charges' in Acquiring Possession",
        year=1973,
        relevance="Transportation and other necessary charges to acquire possession of goods are inventoriable costs",
        key_holding="The cost of merchandise purchased for resale includes the invoice price less trade discounts plus transportation or other necessary charges incurred in acquiring possession of the goods. 'Necessary charges' has been interpreted broadly by the IRS and courts to include any cost directly linked to acquiring specific inventory items.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["inventory", "cost", "necessary charges", "acquisition", "freight", "1.471-3(b)"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 81-272, 1981-2 C.B. 111",
        authority_type="rev_rul",
        title="Sales-Service Fees — Must Be Inventoried",
        year=1981,
        relevance="Fees paid to wholesaler based on volume of goods purchased must be included in inventory cost",
        key_holding="Fees paid to a wholesaler or supplier that are volume-based (calculated as a percentage of purchases) must be inventoried as part of the cost of the goods, even if the buyer characterizes the fee as payment for 'services rendered.' The economic substance — a cost directly tied to acquiring specific inventory — governs over the label applied.",
        facts_summary="The IRS rejected the taxpayer's argument that volume-based fees were deductible service costs. The ruling establishes that when a fee bears a direct relationship to the acquisition of specific goods, its character as a 'service fee' does not prevent it from being an inventory cost.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["inventory", "sales-service fees", "volume fees", "acquisition cost", "Rev. Rul. 81-272"],
    ),
    TechnicalAuthority(
        citation="Letter Ruling 8418009",
        authority_type="plr",
        title="Letter of Credit Fees — Inventoriable Cost",
        year=1984,
        relevance="Bank letter of credit fees in international trade transactions must be capitalized to inventory",
        key_holding="Setup fees and acceptance fees charged by banks in connection with letters of credit used to finance the purchase of imported goods must be inventoried as part of the cost of the goods. The fees have a direct relationship to acquiring specific inventory items and are not general financing costs.",
        taxpayer_favorable=False,
        weight="some",
        topics=["inventory", "letter of credit", "LC fees", "import", "acquisition cost", "capitalization"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-3(b) — Customs/Import Duties",
        authority_type="regulation",
        title="Customs and Import Duties — Part of Inventory Cost",
        year=1973,
        relevance="Federal customs and tariff duties paid on imported raw materials must be added to inventory cost",
        key_holding="Customs duties, import tariffs, and related fees paid on imported materials are part of the cost of acquiring possession of the goods and must be capitalized as part of inventory cost. These are 'necessary charges' under Reg. §1.471-3(b).",
        taxpayer_favorable=False,
        weight="primary",
        topics=["inventory", "customs", "import duties", "tariffs", "acquisition cost"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 81-272 — Field Purchasing Costs",
        authority_type="rev_rul",
        title="Field Purchasing Commissions, Hauling, and Freight — Inventoriable",
        year=1981,
        relevance="Commissions to buyers and transportation costs to acquire raw goods are inventory costs",
        key_holding="Commissions paid to buyers and amounts paid for hauling, loading, and freight incurred after acquiring title to raw goods (such as agricultural products purchased in the field) are costs of acquiring possession and must be inventoried. The costs are not deductible as selling or procurement expenses.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["inventory", "commissions", "hauling", "freight", "field purchasing", "acquisition"],
    ),

    # --- Taxes and Government Assessments ---
    TechnicalAuthority(
        citation="TAM 200437035",
        authority_type="tam",
        title="State Tax Stamps — Inventoriable Handling/Storage Costs",
        year=2004,
        relevance="State tax stamps affixed to cigarettes are capitalizable inventory costs, not deductible selling expenses",
        key_holding="The cost of state tax stamps that must be affixed to cigarette packages must be treated as inventoriable handling or storage costs under §263A, rather than deductible selling expenses. The stamps are required to make the goods saleable in the applicable jurisdiction and are directly associated with specific inventory items.",
        taxpayer_favorable=False,
        weight="some",
        topics=["263A", "tax stamps", "cigarettes", "handling costs", "capitalizable", "TAM 200437035"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-2(a)(2)(ii) — Impact Fees",
        authority_type="regulation",
        title="Municipal Impact Fees — Must Be Capitalized to Constructed Property",
        year=1993,
        relevance="Impact fees paid to municipalities for development approval must be capitalized",
        key_holding="Fees assessed by municipalities against real estate developers to secure approval to develop land (impact fees, infrastructure fees, development fees) must be capitalized into the cost of the constructed property under §263A. These fees are direct costs of producing the property.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "impact fees", "real estate", "development", "capitalization"],
    ),

    # --- Environmental and Legal Costs ---
    TechnicalAuthority(
        citation="Rev. Rul. 94-38, 1994-1 C.B. 35",
        authority_type="rev_rul",
        title="Environmental Remediation Costs — Capitalizable vs. Deductible",
        year=1994,
        relevance="Environmental cleanup costs that are a direct result of manufacturing must be capitalized to inventory",
        key_holding="Environmental cleanup costs that arise as a direct result of a taxpayer's manufacturing or production processes must be capitalized to inventory as indirect production costs under §263A. However, cleanup costs related to products already sold to customers (product liability) remain deductible period costs under §162. The distinction turns on whether the contamination is contemporaneous with current production.",
        facts_summary="This is a contested area. Some courts have allowed deductions for environmental costs while the IRS often argues capitalization. The key distinction: contamination from current production = capitalize; contamination from past operations = potentially deductible.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["263A", "environmental cleanup", "remediation", "production costs", "Rev. Rul. 94-38"],
    ),

    # --- Employee Benefits and Labor Overheads ---
    TechnicalAuthority(
        citation="GCM 34547",
        authority_type="gcm",
        title="ESOP Dividends — Employee Benefit That Must Be Allocated to Inventory",
        year=1971,
        relevance="ESOP dividends paid to production employees are employee benefits that must be inventoried",
        key_holding="Dividends paid to employees through an Employee Stock Ownership Plan (ESOP) constitute an employee benefit that must be allocated between capitalizable (production-related) activities and deductible (non-production) activities. The portion attributable to production workers must be capitalized into inventory costs under the full absorption rules.",
        taxpayer_favorable=False,
        weight="some",
        topics=["263A", "ESOP", "dividends", "employee benefits", "inventory", "GCM 34547"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(e)(3)(ii)(G) — Pension and Unemployment Benefits",
        authority_type="regulation",
        title="Pension and Supplementary Unemployment Benefits — Indirect Production Costs",
        year=1993,
        relevance="Pension contributions and supplementary unemployment benefits are capitalizable indirect costs",
        key_holding="Contributions to pension plans and supplementary unemployment benefit plans attributable to production workers are indirect costs that must be capitalized under §263A. Pension costs for production employees are an employee benefit cost explicitly listed as capitalizable in the §263A regulations.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "pension", "unemployment benefits", "employee benefits", "indirect costs"],
    ),
    TechnicalAuthority(
        citation="Wikstrom & Sons v. Commissioner, T.C. Memo 1961-264",
        authority_type="case_law",
        title="Wikstrom — Niche Overhead Items Forced into Inventory",
        year=1961,
        relevance="Court required capitalization of 'employees' welfare' and 'factory stores' as inventory overhead",
        key_holding="The Tax Court required the taxpayer to capitalize employees' welfare costs and factory store costs as part of manufacturing overhead. Employees' welfare costs included the expense of operating recreational facilities and other amenities for production employees. Factory store costs (company store operated for employee convenience) were similarly required to be capitalized as part of the cost of production.",
        facts_summary="This early case established the broad scope of 'overhead' for inventory costing purposes. The decision illustrates that any cost directly associated with maintaining the production workforce can be a capitalizable overhead item.",
        taxpayer_favorable=False,
        weight="some",
        topics=["inventory", "overhead", "employee welfare", "factory stores", "Wikstrom"],
    ),

    # --- Industry-Specific Costs ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-8(c)(2) — Oil and Gas Delay Rentals",
        authority_type="regulation",
        title="Delay Rentals — Capitalizable to Accumulated Production Expenditures (Oil & Gas)",
        year=1992,
        relevance="Delay rental payments for oil/gas leaseholds must be capitalized during production period",
        key_holding="In the oil and gas industry, delay rentals paid to maintain an oil and gas leasehold during the period before production commences must be included in the accumulated production expenditures of the property under §263A(f). These are carrying costs for the property being produced and must be capitalized into the property's basis.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A(f)", "oil and gas", "delay rentals", "accumulated expenditures", "production period"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-9(a)(3) — Loan Commitment Fees",
        authority_type="regulation",
        title="Loan Commitment Fees — Capitalizable Under §263A(f) Interest Rules",
        year=1992,
        relevance="Commitment fees for construction loans must be capitalized as interest under §263A(f)",
        key_holding="Commitment fees paid to a lender in preparation for drawing down loan proceeds to finance construction of property are treated as interest under the §263A(f) interest capitalization rules. These fees must be capitalized as part of the cost of the constructed property, not deducted currently under §162.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A(f)", "loan commitment fees", "interest capitalization", "construction loans"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 53-141, 1953-2 C.B. 134",
        authority_type="rev_rul",
        title="Aging Costs for Whiskey — Indirect Production Costs",
        year=1953,
        relevance="Storage, insurance, and taxes during whiskey aging period are capitalizable production costs",
        key_holding="The costs of aging whiskey — including warehouse storage costs, insurance premiums, and property taxes during the aging period — constitute indirect production costs incident to the production of the liquor and must be inventoried. These costs are necessary to bring the product to its finished state and cannot be deducted as current period expenses.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["inventory", "whiskey", "aging", "storage", "insurance", "indirect costs", "Rev. Rul. 53-141"],
    ),
    TechnicalAuthority(
        citation="Robinson Knife Manufacturing Co. v. Commissioner, 600 F.3d 121 (2d Cir. 2010)",
        authority_type="case_law",
        title="Robinson Knife — Royalties Must Be Included in Inventory Cost",
        year=2010,
        relevance="Royalties paid for the right to use technology in manufacturing must be capitalized to inventory",
        key_holding="The Second Circuit held that royalties paid by a manufacturer for the right to use patented technology in its manufacturing process must be capitalized as part of the cost of goods produced. The royalties are a direct production cost because they are incurred specifically to produce each unit of product. The court rejected the taxpayer's argument that the royalties were deductible license fees under §162.",
        facts_summary="Robinson Knife paid royalties based on units produced under a patent license. The court's analysis focused on whether the royalties were necessary to produce each unit — they were, so they were inventoriable production costs.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["inventory", "royalties", "manufacturing", "direct production costs", "Robinson Knife"],
    ),

    # --- Departmental Costs ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(e)(3)(ii)(T)",
        authority_type="regulation",
        title="Purchasing Department Costs — Capitalizable",
        year=1993,
        relevance="Purchasing and procurement department costs are indirect costs that must be capitalized",
        key_holding="Costs incurred in the purchasing department — including selecting merchandise, maintaining stock assortment, placing orders, vendor relations, and expediting delivery — are indirect costs required to be capitalized under §263A. This covers both buyer salaries and overhead associated with the purchasing function.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "purchasing department", "procurement", "indirect costs", "capitalizable"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(e)(3)(ii)(U)",
        authority_type="regulation",
        title="Handling, Processing, Assembly, and Storage Costs — Capitalizable",
        year=1993,
        relevance="Internal handling, processing, assembly, and off-site storage costs must be capitalized",
        key_holding="Costs incurred in handling, processing, assembling, and storing inventory — including costs of moving goods within a warehouse, repackaging, and off-site storage — are indirect production/resale costs required to be capitalized. On-site retail storage (the floor or stockroom of a retail store) is specifically excluded.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "handling costs", "processing", "assembly", "storage", "off-site storage"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(e)(3)(ii)(E) — Quality Control",
        authority_type="regulation",
        title="Quality Control and Inspection Costs — Capitalizable",
        year=1993,
        relevance="Quality control testing and inspection of production outputs must be capitalized",
        key_holding="Costs incurred in quality control and inspection — including testing of raw materials, in-process goods, and finished goods — are indirect production costs required to be capitalized under §263A. This includes costs of QC personnel, equipment, and laboratory testing.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "quality control", "inspection", "testing", "indirect costs"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(e)(3)(ii)(A) — Depreciation",
        authority_type="regulation",
        title="Depreciation on Production Assets — Must Be Capitalized to Inventory",
        year=1993,
        relevance="Depreciation, amortization, and depletion on production assets are capitalizable overhead",
        key_holding="Depreciation (§168 MACRS), amortization, and depletion deductions on assets used in production must be capitalized as indirect production costs under §263A. This means the depreciation deduction on production equipment does not reduce taxable income directly — instead, it flows through inventory and becomes COGS when the goods are sold.",
        facts_summary="This is often the largest single component of additional §263A costs for manufacturers. Pre-TCJA bonus depreciation that generated large §168(k) deductions required significant §263A capitalization adjustments.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "depreciation", "MACRS", "production assets", "indirect costs", "overhead"],
    ),
    TechnicalAuthority(
        citation="Idaho Power Co. v. Commissioner, 418 U.S. 1 (1974)",
        authority_type="case_law",
        title="Idaho Power — Depreciation on Construction Equipment Must Be Capitalized",
        year=1974,
        relevance="Supreme Court held depreciation on equipment used in self-construction must be capitalized into asset cost",
        key_holding="The Supreme Court held that depreciation on equipment used in the self-construction of capital assets must be capitalized as part of the cost of the constructed assets rather than deducted currently. This principle was later codified in the §263A interest capitalization rules and the general UNICAP framework.",
        facts_summary="Idaho Power constructed its own utility infrastructure using trucks and equipment. The IRS required capitalization of depreciation on these assets into the infrastructure cost. The Supreme Court agreed, establishing the fundamental principle underlying §263A.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["depreciation", "capitalization", "self-constructed assets", "Idaho Power", "263A"],
    ),
]
