"""Inventory-related case law authorities.

Covers landmark Supreme Court, circuit court, and Tax Court decisions on
inventory valuation, LIFO, UNICAP, cost of goods sold, and related issues.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from revenue_recognition.technical_authority.authorities.base import TechnicalAuthority

INVENTORY_CASE_LAW = [
    # --- Supreme Court ---
    TechnicalAuthority(
        citation="Thor Power Tool Co. v. Commissioner, 439 U.S. 522 (1979)",
        authority_type="case_law",
        title="Thor Power Tool — Write-Down to Net Realizable Value Disallowed",
        year=1979,
        relevance="GAAP inventory write-downs do not automatically satisfy 'clearly reflect income' standard",
        key_holding="The Supreme Court held that a manufacturer could not write down excess and obsolete inventory to net realizable value for tax purposes solely because GAAP required such treatment. For tax purposes, inventory must independently satisfy the 'clearly reflect income' standard. Write-downs of excess inventory require more than projected inability to sell at normal prices — there must be actual price reductions or objective evidence of unsaleability.",
        facts_summary="Thor Power Tool wrote down excess spare parts and finished goods inventory under GAAP. The IRS disallowed the write-downs. The Supreme Court upheld the IRS, emphasizing that tax and financial accounting serve different purposes and GAAP conformity is not sufficient for tax purposes.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["inventory", "write-down", "NRV", "obsolete", "clearly reflect income", "GAAP vs tax", "Thor Power Tool"],
    ),
    TechnicalAuthority(
        citation="Lucas v. Kansas City Structural Steel Co., 281 U.S. 264 (1930)",
        authority_type="case_law",
        title="Kansas City Structural Steel — Base Stock Method Rejected",
        year=1930,
        relevance="Base stock (normal stock) inventory method does not clearly reflect income",
        key_holding="The Supreme Court rejected the base stock method of inventory accounting (where a core or 'base' stock is maintained at a fixed historical cost and only fluctuations above that base are inventoried at current cost). The method was held to not clearly reflect income because it permanently deferred recognition of gains attributable to the base stock.",
        facts_summary="This case predates LIFO but established that the IRS has broad authority to reject inventory methods that do not clearly reflect income. The base stock method, a precursor to LIFO, was rejected because it allowed permanent deferral rather than just timing differences.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["inventory", "base stock method", "clearly reflect income", "Kansas City Structural Steel"],
    ),
    TechnicalAuthority(
        citation="Idaho Power Co. v. Commissioner, 418 U.S. 1 (1974)",
        authority_type="case_law",
        title="Idaho Power — Depreciation on Construction Equipment Must Be Capitalized",
        year=1974,
        relevance="Depreciation on equipment used in self-construction must be capitalized into asset cost, not deducted currently",
        key_holding="The Supreme Court held that allowances for depreciation on equipment used in constructing capital assets must be capitalized as part of the cost of the constructed assets. The decision rejected the taxpayer's argument that §167 required a current deduction, holding that §263 requires capitalization of construction costs including depreciation.",
        facts_summary="Idaho Power used its own equipment to construct transmission lines and other utility infrastructure. The Court's decision established the foundation for the §263A interest capitalization rules and the inclusion of depreciation in UNICAP costs.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["depreciation", "self-constructed assets", "capitalization", "Idaho Power"],
    ),

    # --- Circuit Courts ---
    TechnicalAuthority(
        citation="La Crosse Footwear, Inc. v. United States, 46 Fed. Cl. 380 (2000)",
        authority_type="case_law",
        title="La Crosse Footwear — Dollar-Value LIFO Pool Determination",
        year=2000,
        relevance="Dollar-value LIFO pools must reflect natural business units",
        key_holding="The court examined whether La Crosse Footwear properly maintained separate LIFO pools for different product lines. The decision addressed the natural business unit (NBU) pooling rules and the circumstances under which a manufacturer may maintain multiple pools versus a single enterprise-wide pool.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "dollar-value", "pooling", "natural business unit", "La Crosse Footwear"],
    ),
    TechnicalAuthority(
        citation="Robinson Knife Manufacturing Co. v. Commissioner, 600 F.3d 121 (2d Cir. 2010)",
        authority_type="case_law",
        title="Robinson Knife — Royalties Are Inventory Costs",
        year=2010,
        relevance="Patent royalties paid for right to use manufacturing technology must be capitalized to inventory",
        key_holding="The Second Circuit held that royalties paid on a per-unit-produced basis for the right to use patented manufacturing technology are direct production costs that must be capitalized to inventory under §263A. The royalties are not deductible license fees under §162 because they are incurred specifically to produce each unit of product.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["inventory", "royalties", "263A", "direct costs", "manufacturing", "Robinson Knife"],
    ),
    TechnicalAuthority(
        citation="Suzy's Zoo v. Commissioner, 273 F.3d 875 (9th Cir. 2001)",
        authority_type="case_law",
        title="Suzy's Zoo — UNICAP 'Producer' Definition; IRS Method Upheld",
        year=2001,
        relevance="Taxpayer contracting out production is still a 'producer' subject to §263A",
        key_holding="The Ninth Circuit affirmed that a company that designs artwork and contracts with third parties to produce finished goods is a 'producer' for §263A purposes. The taxpayer bears the burden of proving its §263A cost allocation method is reasonable. The IRS's alternative method was upheld where the taxpayer failed to demonstrate its method properly allocated indirect costs.",
        facts_summary="Suzy's Zoo licensed its cartoon artwork and had third parties manufacture cards, gifts, and other items. The court held the company was a producer because it bore the economic risk of production.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["263A", "producer", "contract manufacturing", "economic risk", "Suzy's Zoo"],
    ),
    TechnicalAuthority(
        citation="Huffman v. Commissioner, 978 F.2d 1139 (9th Cir. 1992)",
        authority_type="case_law",
        title="Huffman — LIFO Increment Valuation Method",
        year=1992,
        relevance="Determination of proper cost to assign to LIFO increments",
        key_holding="The Ninth Circuit addressed how to value LIFO increments when goods are acquired at varying prices during the year. The court examined whether taxpayers must use most-recent-purchase prices, earliest-acquisition prices, or some average for valuing LIFO increments. The decision provides guidance on permissible methods for assigning costs to new LIFO layers.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "increment", "valuation", "cost assignment", "Huffman"],
    ),
    TechnicalAuthority(
        citation="Space Controls, Inc. v. Commissioner, 322 F.2d 144 (5th Cir. 1963)",
        authority_type="case_law",
        title="Space Controls — Writedowns on Fixed-Price Contracts",
        year=1963,
        relevance="Inventory writedown on fixed-price contract where cost exceeds contract price may be permissible",
        key_holding="The Fifth Circuit held that a manufacturer could write down work-in-process inventory where the total estimated cost of completion exceeded the fixed contract price, resulting in an anticipated loss. The writedown was permitted as a reflection of the actual value of the inventory (which had no value above contract price) and clearly reflected income.",
        facts_summary="This case represents an exception to the general rule that projected losses do not justify writedowns. A fixed-price contract with a locked-in loss creates objective evidence that the inventory is worth less than cost.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["inventory", "writedown", "fixed-price contract", "loss contract", "Space Controls"],
    ),
    TechnicalAuthority(
        citation="Joseph E. Seagram & Sons, Inc. v. Commissioner, 394 F.2d 738 (2d Cir. 1968)",
        authority_type="case_law",
        title="Seagram — LIFO Layers in §351 Transfers",
        year=1968,
        relevance="Transferee corporation in §351 does not inherit transferor's LIFO history for layer calculation",
        key_holding="The Second Circuit held that when a LIFO taxpayer transfers inventory to a controlled corporation in a §351 exchange, the receiving corporation cannot inherit the transferor's LIFO layers. The transferred inventory represents a new acquisition to the transferee, establishing a new LIFO base year at the transferred basis.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["LIFO", "351 transfer", "LIFO layers", "carryover basis", "Seagram"],
    ),

    # --- Tax Court ---
    TechnicalAuthority(
        citation="Hamilton Industries, Inc. v. Commissioner, 97 T.C. 120 (1991)",
        authority_type="case_law",
        title="Hamilton Industries — LIFO Layers in Bargain Purchase Transactions",
        year=1991,
        relevance="LIFO base-year values in bargain purchase must reflect actual cost paid, not FMV",
        key_holding="The Tax Court held that when a taxpayer acquires inventory in a bargain purchase (cost below FMV), the LIFO base-year value must be established at actual cost paid, not at FMV. The court rejected the taxpayer's argument for a FMV step-up at acquisition, holding that LIFO layer values reflect actual acquisition cost.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["LIFO", "bargain purchase", "base-year value", "acquisition cost", "Hamilton Industries"],
    ),
    TechnicalAuthority(
        citation="Mountain State Ford Truck Sales, Inc. v. Commissioner, 84 T.C. 28 (1985)",
        authority_type="case_law",
        title="Mountain State Ford — LIFO Replacement Cost for New Vehicles",
        year=1985,
        relevance="New vehicle dealers may use most-recent-purchase price for LIFO increment valuation",
        key_holding="The Tax Court held that a new vehicle dealer properly valued LIFO increments using the most-recent-purchase (replacement cost) method. The court rejected the IRS's argument that the dealer must use an average cost or earliest-purchase method. For dealers where each unit is unique, replacement cost accurately reflects the cost of the most recently acquired vehicles.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "vehicles", "replacement cost", "dealers", "increment valuation", "Mountain State Ford"],
    ),
    TechnicalAuthority(
        citation="Galedrige Construction, Inc. v. Commissioner, T.C. Memo 1997-240",
        authority_type="case_law",
        title="Galedrige — Emulsified Asphalt Treated as Inventory, Not Supplies",
        year=1997,
        relevance="Materials used in construction projects must be inventoried, not deducted as supplies",
        key_holding="The Tax Court held that emulsified asphalt and other materials used by a construction company in building roads were inventory items, not materials and supplies deductible under §162. The materials were income-producing factors requiring inventory accounting under §471.",
        taxpayer_favorable=False,
        weight="some",
        topics=["inventory", "construction", "materials", "supplies", "Galedrige"],
    ),
    TechnicalAuthority(
        citation="Marcor, Inc. v. Commissioner, 89 T.C. 1267 (1987)",
        authority_type="case_law",
        title="Marcor — Definition of Cost of Goods Sold",
        year=1987,
        relevance="Proper components of cost of goods sold for a retailer under §471",
        key_holding="The Tax Court examined what costs could properly be included in cost of goods sold for a large retailer. The court addressed the treatment of store opening costs, buying office expenses, and various overhead items. Costs that are primarily selling or administrative in nature cannot be included in COGS even if they are incurred in connection with acquiring inventory.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["inventory", "COGS", "cost of goods sold", "retailer", "overhead", "Marcor"],
    ),
    TechnicalAuthority(
        citation="Dayton Hudson Corp. v. Commissioner, 101 T.C. 462 (1993)",
        authority_type="case_law",
        title="Dayton Hudson — Shrinkage Reserves and Retail Inventory Method",
        year=1993,
        relevance="Estimated shrinkage reserve deducted under retail inventory method must be objectively determinable",
        key_holding="The Tax Court held that a retailer may include estimated shrinkage (theft, breakage, administrative error) in its retail inventory method computation, provided the estimate is based on historical experience with a physical inventory taken at year-end. The court required objective verification of the shrinkage estimate.",
        facts_summary="Dayton Hudson used the retail inventory method and included an estimated shrinkage allowance to reduce ending inventory. The court allowed the practice as consistent with best accounting practice and clearly reflecting income, provided the estimate was based on reliable historical data.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["inventory", "shrinkage", "retail inventory method", "estimation", "Dayton Hudson"],
    ),
    TechnicalAuthority(
        citation="Hutzler Bros. Co. v. Commissioner, 8 T.C. 14 (1947)",
        authority_type="case_law",
        title="Hutzler Bros. — Retail LIFO Method",
        year=1947,
        relevance="Retailers may combine LIFO with retail inventory method",
        key_holding="The Tax Court approved the use of LIFO in conjunction with the retail inventory method (LIFO retail). Under this approach, inventory is valued using the retail method to determine beginning and ending inventory at both cost and retail, and then LIFO adjustments are applied to the retail amounts. This combination is now expressly permitted under Reg. §1.472-1.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "retail inventory method", "LIFO retail", "retailers", "Hutzler Bros."],
    ),
    TechnicalAuthority(
        citation="Klein Chocolate Co. v. Commissioner, 6 T.C. 290 (1946)",
        authority_type="case_law",
        title="Klein Chocolate — LIFO Pooling Requirements",
        year=1946,
        relevance="LIFO taxpayer must maintain consistent pools and cannot cherry-pick items",
        key_holding="The Tax Court held that a LIFO taxpayer must apply the election consistently to all goods in a designated pool. A taxpayer cannot selectively include favorable items in LIFO pools while excluding unfavorable items. The election must apply to the entire inventory of a natural business unit.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["LIFO", "pooling", "consistency", "election", "Klein Chocolate"],
    ),
]
