"""Inventory valuation technical authorities.

Covers §471 valuation methods, lower of cost or market, subnormal goods,
retail inventory method, full absorption method, cost or market, and
specific valuation rules for manufacturers, retailers, and farmers.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from revenue_recognition.technical_authority.authorities.base import TechnicalAuthority

INVENTORY_VALUATION_AUTHORITIES = [
    # --- §471 Regulations ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-2(a)",
        authority_type="regulation",
        title="Inventories — Best Accounting Practice and Clear Reflection",
        year=1973,
        relevance="Inventory method must conform to best accounting practice and clearly reflect income",
        key_holding="The primary test for an inventory method is whether it (1) conforms as nearly as possible to the best accounting practice in the trade or business, and (2) most clearly reflects income. The IRS has broad authority to reject an inventory method that does not satisfy both standards, even if the method is acceptable under GAAP.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["inventory", "471", "best accounting practice", "clearly reflect income", "1.471-2"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-2(b)",
        authority_type="regulation",
        title="Inventory — Subnormal Goods",
        year=1973,
        relevance="Damaged, obsolete, or shop-worn goods may be valued below cost",
        key_holding="Goods that are unsalable at normal prices due to damage, imperfections, shop wear, changes in style, odd or broken lots, or other causes may be valued at a bona fide selling price less direct cost of disposal, rather than at cost or LCM. The reduced value must reflect actual offering price or evidence of inability to sell at normal prices.",
        facts_summary="This provision was at the heart of Thor Power Tool — the Supreme Court held that projected inability to sell at normal prices is insufficient; there must be actual reduction in selling price or other objective evidence.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["inventory", "subnormal goods", "damaged goods", "obsolete", "writedown", "1.471-2(b)"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-3",
        authority_type="regulation",
        title="Inventories at Cost — What Constitutes Cost",
        year=1973,
        relevance="Definition of inventory cost for producers and resellers",
        key_holding="For merchandise purchased: cost is invoice price minus trade discounts plus freight and other charges. For goods produced: cost includes raw materials, direct labor, and overhead (indirect production costs under full absorption). Does not include selling expenses, general administrative expenses, or interest.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["inventory", "cost", "invoice price", "freight", "overhead", "1.471-3"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-4",
        authority_type="regulation",
        title="Inventories at Lower of Cost or Market (LCM)",
        year=1973,
        relevance="LCM valuation — market means replacement cost (not NRV) for most goods",
        key_holding="Under the LCM method, 'market' generally means the current bid price or current replacement cost at the inventory date. For finished goods and work-in-process produced by the taxpayer, market is the price at which goods are offered for sale in the normal course of business. Under the LCM method, each item is compared to its market price independently.",
        facts_summary="Important distinction: for purchased goods, 'market' is replacement cost (cost to buy the goods again); for produced goods, 'market' is the price in the current market for that type of finished goods.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["inventory", "LCM", "lower of cost or market", "replacement cost", "market value", "1.471-4"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-6",
        authority_type="regulation",
        title="Inventories of Livestock Raisers and Farmers",
        year=1973,
        relevance="Farmers may use farm-price method or unit-livestock-price method for inventory",
        key_holding="Livestock raisers and farmers may value inventories using: (1) the farm-price method (FMV less direct cost of disposition), or (2) the unit-livestock-price method (standard costs per animal category, updated periodically). These methods avoid the complexity of tracking actual costs for each animal.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["inventory", "farming", "livestock", "farm-price method", "unit-livestock-price", "1.471-6"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-8",
        authority_type="regulation",
        title="Retail Inventory Method",
        year=1973,
        relevance="Retailers may compute inventory cost using cost-to-retail ratio",
        key_holding="Retailers may use the retail inventory method, which estimates cost by applying a cost-to-retail ratio to the retail value of ending inventory. The ratio is computed as (beginning inventory at cost + purchases at cost) / (beginning inventory at retail + purchases at retail). May also use LIFO retail method combining retail method with LIFO.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["inventory", "retail inventory method", "cost-to-retail ratio", "retailers", "1.471-8"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.471-11",
        authority_type="regulation",
        title="Inventories of Manufacturers — Full Absorption Costing",
        year=1973,
        relevance="Manufacturers must use full absorption costing, including fixed and variable overhead",
        key_holding="Manufacturers must use full absorption inventory costing, which requires including all direct costs (materials, labor) plus fixed and variable manufacturing overhead in inventory. Fixed overhead includes depreciation, insurance, property taxes, rent, and supervisory salaries. Pre-§263A full absorption was the predecessor to UNICAP.",
        facts_summary="§263A largely replaced §1.471-11 for taxpayers subject to UNICAP, but §1.471-11 remains relevant for determining §471 costs (the base amount before §263A adjustments) under the simplified production method.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["inventory", "full absorption", "manufacturers", "overhead", "1.471-11"],
    ),

    # --- IRC §475 ---
    TechnicalAuthority(
        citation="IRC §475",
        authority_type="statute",
        title="§475 Mark-to-Market Accounting for Securities Dealers",
        year=1993,
        relevance="Securities dealers must mark inventory securities to market annually",
        key_holding="Dealers in securities must recognize gain or loss on any security held at year end as if the security were sold for its fair market value on the last business day of the taxable year. This is a mandatory mark-to-market method for securities inventory. Gain or loss is ordinary income or loss.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["475", "mark-to-market", "securities dealers", "inventory", "ordinary income"],
    ),

    # --- IRC §280E ---
    TechnicalAuthority(
        citation="IRC §280E",
        authority_type="statute",
        title="§280E — Expenditures in Connection with Illegal Drug Sales",
        year=1982,
        relevance="Cannabis businesses cannot deduct ordinary business expenses but can deduct COGS (inventory)",
        key_holding="No deduction or credit is allowed for any amount paid or incurred in carrying on a trade or business consisting of trafficking in controlled substances prohibited under federal law. However, §280E does not disallow the deduction for cost of goods sold — only business deductions under §162 are denied. Cannabis businesses can still reduce income by COGS.",
        facts_summary="Cannabis businesses must carefully segregate their §263A UNICAP costs and ensure that amounts included in COGS are properly inventoried. The interaction of §280E and §263A is a major compliance issue for the industry.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["280E", "cannabis", "marijuana", "COGS", "controlled substances", "deduction disallowance"],
    ),

    # --- §471 Additional Guidance ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.61-3",
        authority_type="regulation",
        title="Gross Income from Business — Inventory and Cost of Goods Sold",
        year=1957,
        relevance="Gross income from business = gross sales minus cost of goods sold",
        key_holding="In a manufacturing, merchandising, or mining business, gross income means the total sales minus the cost of goods sold. Cost of goods sold includes all direct costs of production or purchase and allocable indirect costs. Selling expenses, losses, and other non-production costs are not included in COGS.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["gross income", "COGS", "cost of goods sold", "inventory", "1.61-3"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.162-3",
        authority_type="regulation",
        title="Materials and Supplies — Deduction Rules",
        year=2013,
        relevance="Materials and supplies deducted when consumed or used; incidental supplies when purchased",
        key_holding="The cost of materials and supplies is deductible: (1) for non-incidental materials and supplies, when actually consumed or used; (2) for incidental materials and supplies, in the year purchased if amount is consistently charged to expense. This regulation interacts with §263A — materials used in production must be inventoried rather than deducted as supplies.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["materials", "supplies", "deduction", "1.162-3", "consumed", "purchased"],
    ),
    TechnicalAuthority(
        citation="IRC §266",
        authority_type="statute",
        title="§266 — Carrying Charges; Election to Capitalize",
        year=1954,
        relevance="Taxpayers may elect to capitalize carrying charges (taxes, interest) on unimproved real property and similar assets",
        key_holding="A taxpayer may elect to capitalize carrying charges (annual taxes, interest, other carrying charges) on: (1) unimproved and unproductive real property, (2) real property being developed, (3) personal property before production commences. Once capitalized, these amounts increase basis rather than being deducted currently.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["266", "carrying charges", "capitalize", "real property", "interest", "taxes"],
    ),

    # --- Accounting Methods Interaction ---
    TechnicalAuthority(
        citation="IRC §447",
        authority_type="statute",
        title="§447 — Method of Accounting for Farming Corporations",
        year=1976,
        relevance="C corporations and partnerships with C corporation partners in farming must use accrual method",
        key_holding="A C corporation (or partnership with a C corporation partner) engaged in the business of farming must use the accrual method of accounting. Exception: S corporations, family farming corporations with gross receipts of $1M or less, and corporations formed before 1976. Applies to inventory of farming operations.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["447", "farming corporations", "accrual method", "C corporation"],
    ),
    TechnicalAuthority(
        citation="Rev. Proc. 2002-28, 2002-1 C.B. 815",
        authority_type="rev_proc",
        title="Small Business Taxpayers — Accounting Methods; Cash Method for Small Resellers",
        year=2002,
        relevance="Small businesses with average gross receipts ≤$10M may use cash method for inventory",
        key_holding="Pre-TCJA safe harbor allowing small businesses with average annual gross receipts of $10M or less to use the cash receipts and disbursements method. Under this safe harbor, qualifying businesses are not required to maintain inventories under §471. The TCJA later expanded this threshold significantly via §448(c) and §471(c).",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["small business", "cash method", "inventory", "Rev. Proc. 2002-28", "10M threshold"],
    ),
    TechnicalAuthority(
        citation="Notice 2009-25, 2009-1 C.B. 753",
        authority_type="notice",
        title="Retail Inventory Method — Safe Harbor for Handling Costs",
        year=2009,
        relevance="Safe harbor treatment for certain handling costs under simplified resale method",
        key_holding="Provides a safe harbor under which retailers using the simplified resale method may include or exclude certain handling costs from their §263A computation on an annual basis without a formal method change, provided the method is consistently applied within the year.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["263A", "retail", "handling costs", "safe harbor", "Notice 2009-25"],
    ),
]
