"""Inventory administrative guidance authorities.

Covers Revenue Procedures, Revenue Rulings, Notices, GCMs, TAMs, PLRs,
FSAs, and LB&I practice units related to inventory, LIFO, and UNICAP.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from revenue_recognition.technical_authority.authorities.base import TechnicalAuthority

INVENTORY_ADMIN_GUIDANCE = [
    # --- Revenue Procedures ---
    TechnicalAuthority(
        citation="Rev. Proc. 2015-13, 2015-5 I.R.B. 419",
        authority_type="rev_proc",
        title="Procedures for Voluntary Accounting Method Changes (Pre-2024)",
        year=2015,
        relevance="Automatic and advance consent procedures for inventory method changes",
        key_holding="Provides comprehensive procedures for changing methods of accounting under §446(e). Automatic changes (Appendix) may be made without advance IRS consent. Non-automatic changes require Form 3115 filed with full year return. The §481(a) adjustment is spread over 4 years (unfavorable) or taken currently (favorable). Superseded in part by Rev. Proc. 2024-23.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["method change", "Rev. Proc. 2015-13", "Form 3115", "481(a)", "automatic consent"],
    ),
    TechnicalAuthority(
        citation="Rev. Proc. 2024-23, 2024-16 I.R.B. 869",
        authority_type="rev_proc",
        title="Updated List of Automatic Accounting Method Changes",
        year=2024,
        relevance="Current list of automatic consent method changes including inventory and UNICAP changes",
        key_holding="Provides current consolidated list of automatic method changes. Key inventory changes: (1) §22 — §263A method changes (simplified production, simplified resale, simplified service cost, cost allocation changes); (2) §21 — inventory method changes (LIFO adoption, LCM to cost, §471(c) small business election adoption/revocation); (3) §7 — changes to comply with §448 cash method eligibility.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["method change", "Rev. Proc. 2024-23", "automatic consent", "263A", "LIFO", "471(c)"],
    ),
    TechnicalAuthority(
        citation="Rev. Proc. 2002-18, 2002-1 C.B. 678",
        authority_type="rev_proc",
        title="Accounting Method Changes on Examination — Examination Protection",
        year=2002,
        relevance="Special rules for making method changes while under IRS examination",
        key_holding="Provides rules for IRS agents and taxpayers when accounting method issues arise during examination. Generally, if a taxpayer is under examination and a method change is raised, the taxpayer may request to change the method under Rev. Proc. 2015-13 terms. Distinguishes between method changes (§481 adjustment) and corrections of errors (amended returns).",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["method change", "examination", "Rev. Proc. 2002-18", "IRS audit", "481(a)"],
    ),
    TechnicalAuthority(
        citation="Rev. Proc. 2008-43, 2008-2 C.B. 186",
        authority_type="rev_proc",
        title="Rolling Average Cost Method — Certain Manufacturing Taxpayers",
        year=2008,
        relevance="Safe harbor allowing certain manufacturers to use rolling average cost for inventory",
        key_holding="Provides a safe harbor for certain manufacturing taxpayers to use a rolling average cost method for valuing raw material inventory. Under this method, inventory costs are updated continuously as new purchases are made, using a weighted average of existing inventory cost and new purchase price. Reduces need to track specific purchase lots.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["inventory", "average cost", "rolling average", "manufacturers", "Rev. Proc. 2008-43"],
    ),

    # --- Revenue Rulings ---
    TechnicalAuthority(
        citation="Rev. Rul. 2001-8, 2001-1 C.B. 726",
        authority_type="rev_rul",
        title="Floor Stocks Taxes on LIFO Inventory — Period Cost, Not Layer Adjustment",
        year=2001,
        relevance="Excise taxes on inventory imposed at enactment of new tax are period costs, not LIFO layer adjustments",
        key_holding="Floor stocks taxes (excise taxes imposed on a taxpayer's existing inventory when a new excise tax takes effect) are deductible period costs under §162, not adjustments to LIFO inventory layer costs. The taxes do not represent an acquisition or production cost of the inventory; they are imposed on possession of the goods at a particular date.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "floor stocks tax", "excise tax", "period cost", "Rev. Rul. 2001-8"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 81-272, 1981-2 C.B. 111",
        authority_type="rev_rul",
        title="Contract Manufacturing — Ownership of Goods for §263A Purposes",
        year=1981,
        relevance="Who is the producer for §263A when goods are manufactured under contract",
        key_holding="In a contract manufacturing arrangement, the party that bears the economic risk of loss with respect to the manufactured goods (typically the party that owns the raw materials and bears the risk that the goods will not sell) is treated as the producer for §263A purposes, not the contract manufacturer. Ownership and economic risk determine who must apply UNICAP.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["263A", "contract manufacturing", "producer", "economic risk", "ownership", "Rev. Rul. 81-272"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 76-282, 1976-2 C.B. 136",
        authority_type="rev_rul",
        title="LIFO Adoption — Subnormal Goods Writedown Must Be Restored",
        year=1976,
        relevance="Prior tax writedowns of inventory must be restored to income when LIFO is adopted",
        key_holding="When a taxpayer elects LIFO, any prior writedowns of inventory — including writedowns of subnormal goods — must be restored to income in the LIFO election year. §472(b) requires that opening LIFO inventory be valued at cost, not at any previously written-down amount.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["LIFO", "subnormal goods", "writedown restoration", "election year", "Rev. Rul. 76-282"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 79-290, 1979-2 C.B. 230",
        authority_type="rev_rul",
        title="Dollar-Value LIFO — Method of Valuation, Not Identification",
        year=1979,
        relevance="Dollar-value LIFO governs inventory valuation, not physical identification of goods",
        key_holding="Dollar-value LIFO is a method of valuation, not identification. Accordingly, the LIFO conformity requirement does not prevent a taxpayer from separately identifying specific goods for other legal or business purposes. The dollar-value method measures inventory changes in aggregate dollar terms using price indexes, not by tracing specific physical units.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "dollar-value", "valuation", "identification", "conformity", "Rev. Rul. 79-290"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 70-346, 1970-2 C.B. 21",
        authority_type="rev_rul",
        title="Depreciation in Inventory — Full Absorption Method",
        year=1970,
        relevance="Depreciation on production equipment must be included in manufacturer's inventory cost",
        key_holding="Depreciation on machinery and equipment used in manufacturing must be included in the cost of inventory under the full absorption method (Reg. §1.471-11). The ruling establishes that manufacturing overhead — including depreciation — is a necessary component of inventory cost for manufacturers.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["inventory", "depreciation", "full absorption", "manufacturing overhead", "Rev. Rul. 70-346"],
    ),

    # --- Notices ---
    TechnicalAuthority(
        citation="Notice 88-86, 1988-2 C.B. 401",
        authority_type="notice",
        title="UNICAP — Storage Costs, Mixed Service Costs, and Specific Applications",
        year=1988,
        relevance="Detailed IRS guidance on §263A application to specific cost categories",
        key_holding="Provides guidance on: (1) off-site storage costs must be capitalized; on-site retail storage is excluded; (2) mixed service department costs must be allocated between capitalizable and non-capitalizable activities; (3) costs of a HR/personnel department allocable to production workers are capitalizable; (4) IT systems supporting production are capitalizable; (5) security for production facilities is capitalizable.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["263A", "storage", "mixed service", "HR", "IT", "security", "Notice 88-86"],
    ),
    TechnicalAuthority(
        citation="Notice 88-62, 1988-1 C.B. 548",
        authority_type="notice",
        title="§263A Safe Harbor for Authors, Artists, and Photographers",
        year=1988,
        relevance="Authors and artists may use simplified methods for §263A compliance",
        key_holding="Provides a safe harbor under which authors, artists, and photographers engaged in qualified creative activities may deduct otherwise capitalizable costs under §263A when the related creative work has not yet generated income. Reduces compliance burden for creative professionals.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["263A", "authors", "artists", "photographers", "creative activities", "Notice 88-62"],
    ),
    TechnicalAuthority(
        citation="Notice 89-15, 1989-1 C.B. 647",
        authority_type="notice",
        title="Long-Term Contracts — Interaction with §263A",
        year=1989,
        relevance="Clarifies scope of §460 long-term contract exclusion from §263A",
        key_holding="Provides guidance on the boundary between long-term contracts governed by §460 and inventory production governed by §263A. Property produced under a long-term contract that qualifies under §460 is excluded from §263A. However, raw materials and work-in-process that are not committed to a specific contract may still be subject to §263A.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["263A", "460", "long-term contracts", "exclusion", "Notice 89-15"],
    ),

    # --- Technical Advice Memoranda ---
    TechnicalAuthority(
        citation="TAM 200437035",
        authority_type="tam",
        title="§263A — Treatment of State Tax Stamp Costs",
        year=2004,
        relevance="State excise tax stamps affixed to inventory items are capitalizable costs",
        key_holding="The IRS concluded that the cost of state tax stamps that cigarette manufacturers/distributors must affix to their products are handling/processing costs that must be capitalized under §263A. The stamps are a direct cost of preparing the goods for sale in a particular state and are not selling or marketing expenses.",
        taxpayer_favorable=False,
        weight="some",
        topics=["263A", "tax stamps", "cigarettes", "handling costs", "TAM 200437035"],
    ),
    TechnicalAuthority(
        citation="TAM 200735020",
        authority_type="tam",
        title="§263A — Mixed Service Costs; HR Department Allocation",
        year=2007,
        relevance="Human resources department costs must be allocated between production and non-production activities",
        key_holding="The IRS concluded that HR department costs — including recruiting, hiring, benefits administration, and employee relations — must be allocated between capitalizable (production-related) and non-capitalizable activities using a reasonable allocation method. The portion attributable to production employees and activities must be capitalized under §263A.",
        taxpayer_favorable=False,
        weight="some",
        topics=["263A", "HR department", "mixed service costs", "allocation", "TAM 200735020"],
    ),

    # --- Field Service Advice ---
    TechnicalAuthority(
        citation="FSA 199920002",
        authority_type="fsa",
        title="§263A — Simplified Production Method Computation Issues",
        year=1999,
        relevance="IRS field guidance on common issues in computing simplified production method",
        key_holding="Addresses computation issues under the simplified production method, including: (1) proper identification of additional §263A costs (vs. §471 costs), (2) the absorption ratio denominator (§471 costs minus direct material costs), and (3) treatment of negative additional §263A costs. Emphasizes that the method must result in full capitalization of all required indirect costs.",
        taxpayer_favorable=False,
        weight="some",
        topics=["263A", "simplified production method", "absorption ratio", "computation", "FSA 199920002"],
    ),

    # --- General Counsel Memoranda ---
    TechnicalAuthority(
        citation="GCM 35832",
        authority_type="gcm",
        title="LIFO Conformity — Market Value in Financial Statements",
        year=1974,
        relevance="Disclosure of market value information in financial statements does not necessarily violate LIFO conformity",
        key_holding="A company may disclose the market value (FIFO/replacement cost) of LIFO inventories in supplemental notes to its financial statements without violating the LIFO conformity requirement, provided the primary presentation of inventory in the balance sheet and income statement uses the LIFO method.",
        taxpayer_favorable=True,
        weight="some",
        topics=["LIFO", "conformity", "market value", "supplemental disclosure", "GCM 35832"],
    ),
    TechnicalAuthority(
        citation="GCM 38478",
        authority_type="gcm",
        title="Defining 'Items' for LIFO Pooling",
        year=1980,
        relevance="What constitutes an 'item' for purposes of LIFO pool determination",
        key_holding="Provides IRS guidance on defining 'items' within LIFO pools for dollar-value LIFO. Items must be grouped by their natural characteristics and the economic activity they support. Artificial subdivision of items to achieve favorable LIFO indexing results is not permitted. Taxpayers must apply consistent criteria for defining items across periods.",
        taxpayer_favorable=False,
        weight="some",
        topics=["LIFO", "pooling", "items", "dollar-value", "GCM 38478"],
    ),

    # --- LB&I Practice/Concept Units ---
    TechnicalAuthority(
        citation="LB&I Concept Unit — Interest Capitalization for Self-Constructed Assets",
        authority_type="other",
        title="LB&I Practice Unit — §263A(f) Interest Capitalization Audit Guide",
        year=2016,
        relevance="IRS examination guidance for auditing §263A(f) interest capitalization computations",
        key_holding="Key IRS audit focus areas for interest capitalization: (1) identification of designated property (production period >2 years or cost >$1M), (2) computation of accumulated production expenditures, (3) proper application of avoided cost method, (4) treatment of commitment fees as interest, (5) production period start and end dates, (6) interaction with bonus depreciation.",
        taxpayer_favorable=False,
        weight="some",
        topics=["263A(f)", "interest capitalization", "LB&I", "audit", "designated property"],
    ),
    TechnicalAuthority(
        citation="LB&I Concept Unit — LIFO Pooling (COR-C-018)",
        authority_type="other",
        title="LB&I Practice Unit — LIFO Pooling Audit Guide",
        year=2014,
        relevance="IRS examination guidance for auditing LIFO pool elections and dollar-value computations",
        key_holding="Key IRS audit focus areas for LIFO: (1) natural business unit pool validity, (2) proper IPIC index computation (correct BLS categories), (3) LIFO conformity requirement compliance, (4) treatment of acquisitions and dispositions within LIFO pools, (5) pooling changes as method changes requiring consent, (6) LIFO layer reconstruction issues.",
        taxpayer_favorable=False,
        weight="some",
        topics=["LIFO", "pooling", "IPIC", "LB&I", "audit", "COR-C-018"],
    ),

    # --- BLS Price Indexes ---
    TechnicalAuthority(
        citation="BLS Producer Price Indexes / Consumer Price Indexes — IPIC Method",
        authority_type="other",
        title="Bureau of Labor Statistics Price Indexes for IPIC LIFO Computations",
        year=1981,
        relevance="BLS PPI and CPI indexes are the approved sources for IPIC dollar-value LIFO",
        key_holding="Under Reg. §1.472-8(e)(3), taxpayers using the IPIC method must use Bureau of Labor Statistics (BLS) Producer Price Index (PPI) or Consumer Price Index (CPI) data to compute their LIFO price indexes. The indexes are organized by commodity/product category; taxpayers must properly classify their inventory items into the applicable BLS categories and apply the current-year percentage change.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "IPIC", "BLS", "PPI", "CPI", "price index", "dollar-value LIFO"],
    ),
]
