"""LIFO-specific technical authorities.

Covers §472 LIFO election and conformity, §473 qualified liquidations,
§474 simplified LIFO, dollar-value LIFO, pooling rules, IPIC method,
and related LIFO guidance.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from revenue_recognition.technical_authority.authorities.base import TechnicalAuthority

LIFO_AUTHORITIES = [
    # --- Core LIFO Statutes ---
    TechnicalAuthority(
        citation="IRC §472(a)",
        authority_type="statute",
        title="LIFO — Election and Last-In, First-Out Method",
        year=1986,
        relevance="Taxpayer may elect LIFO; goods on hand treated as acquired in order of most recent acquisition",
        key_holding="A taxpayer may elect to determine the cost of goods in inventory under LIFO. Under LIFO, ending inventory is treated as consisting of goods most recently acquired (or produced), so cost of goods sold reflects the most recent costs. Election is made on Form 970.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "472", "election", "inventory method"],
    ),
    TechnicalAuthority(
        citation="IRC §472(b)",
        authority_type="statute",
        title="LIFO — Valuation of Opening Inventory in Election Year",
        year=1986,
        relevance="Opening inventory in LIFO election year valued at cost",
        key_holding="When a taxpayer elects LIFO, the opening inventory for the election year must be taken at cost. Any prior writedown to market must be restored to income in the election year. This creates a one-time income inclusion upon LIFO adoption.",
        facts_summary="The restoration of writedowns upon LIFO adoption can create a significant tax cost in year one. Taxpayers must weigh this against the long-term benefit of LIFO in an inflationary environment.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["LIFO", "472(b)", "election year", "opening inventory", "writedown restoration"],
    ),
    TechnicalAuthority(
        citation="IRC §472(c)",
        authority_type="statute",
        title="LIFO Conformity Requirement",
        year=1986,
        relevance="LIFO for tax requires LIFO for financial reporting — book conformity",
        key_holding="LIFO may not be used for tax unless the taxpayer also uses LIFO for purposes of its annual financial statements and reports to shareholders, partners, or other proprietors. Supplemental disclosures (e.g., LIFO reserve disclosure in footnotes) are permitted.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["LIFO", "472(c)", "conformity", "book-tax", "financial statements"],
    ),
    TechnicalAuthority(
        citation="IRC §472(d)",
        authority_type="statute",
        title="LIFO — Determination of Cost",
        year=1986,
        relevance="LIFO cost determined using actual cost or other approved method",
        key_holding="Under the LIFO method, the cost of goods most recently acquired or produced is used to value ending inventory layers. The dollar-value LIFO method allows taxpayers to measure inventory in terms of total dollar value rather than specific goods, using price indexes to adjust for inflation.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "dollar-value", "cost determination", "price index"],
    ),
    TechnicalAuthority(
        citation="IRC §472(e)",
        authority_type="statute",
        title="LIFO — Termination and Change from LIFO",
        year=1986,
        relevance="IRS may terminate LIFO election if taxpayer fails conformity requirement",
        key_holding="The IRS may revoke a taxpayer's LIFO election if the taxpayer fails to satisfy the conformity requirement of §472(c). A taxpayer may also voluntarily change from LIFO with IRS consent under §446.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["LIFO", "termination", "conformity violation", "method change"],
    ),
    TechnicalAuthority(
        citation="IRC §473",
        authority_type="statute",
        title="§473 — Qualified Liquidations of LIFO Inventories",
        year=1980,
        relevance="Relief provision for LIFO layer liquidations caused by supply disruptions beyond taxpayer's control",
        key_holding="If a taxpayer using LIFO experiences a qualified liquidation (involuntary reduction due to circumstances beyond its control, such as foreign trade disruption, government embargo, or natural disaster), the taxpayer may elect to restore the liquidated LIFO layers by acquiring replacement goods within 3 years. The income from the layer liquidation is deferred until the replacement period.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "473", "involuntary liquidation", "supply disruption", "replacement period"],
    ),
    TechnicalAuthority(
        citation="IRC §474",
        authority_type="statute",
        title="§474 — Simplified LIFO Method for Small Businesses",
        year=1986,
        relevance="Small businesses may use simplified LIFO using Bureau of Labor Statistics indexes",
        key_holding="Taxpayers with average annual gross receipts of $5M or less for the preceding 3 years may elect the simplified LIFO method. Under this method, a single LIFO pool is used for each business and inventory values are adjusted using publicly available BLS price indexes (PPI or CPI). Eliminates need for internal index calculation.",
        facts_summary="The $5M threshold has not been inflation-adjusted since enactment. Most businesses now exceeding this threshold must use the standard LIFO dollar-value method. The simplified method significantly reduces compliance burden.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "474", "simplified LIFO", "small business", "BLS indexes"],
    ),

    # --- Dollar-Value LIFO Regulations ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.472-8(a)",
        authority_type="regulation",
        title="Dollar-Value LIFO — General Rules and Pooling",
        year=1981,
        relevance="Dollar-value LIFO allows inventory measurement by total dollar value, not physical units",
        key_holding="Under dollar-value LIFO, inventory is measured in terms of total dollar value at base-year prices rather than by specific goods. A taxpayer measures increments or decrements in inventory by comparing the current year-end inventory value at base-year prices to the prior year-end value at base-year prices. Allows use of pools rather than item-by-item tracking.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "dollar-value", "pooling", "base-year price", "1.472-8"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.472-8(b)",
        authority_type="regulation",
        title="Dollar-Value LIFO — Natural Business Unit Pooling",
        year=1981,
        relevance="Rules for establishing and maintaining LIFO inventory pools",
        key_holding="A manufacturer or processor must use a natural business unit (NBU) pool comprising all items entering into the entire inventory investment in a natural business unit. A single enterprise may have multiple NBU pools if it has multiple natural business units. Retailers and wholesalers may use one pool per business.",
        facts_summary="Pool determination is critical because separate pools cannot be combined and LIFO layers are tracked within each pool. Splitting or combining pools requires IRS consent as a method change.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "pooling", "natural business unit", "dollar-value", "1.472-8(b)"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.472-8(e)(3)",
        authority_type="regulation",
        title="Dollar-Value LIFO — IPIC (Inventory Price Index Computation) Method",
        year=1981,
        relevance="Safe harbor method for determining LIFO indexes using published BLS price indexes",
        key_holding="Under the IPIC method, taxpayers may determine their LIFO price index using published BLS Producer Price Index (PPI) or Consumer Price Index (CPI) tables. The method involves categorizing inventory items into BLS categories, computing a weighted average price change, and applying it to determine the current-year index. Provides certainty and reduces audit risk.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "IPIC", "price index", "BLS", "PPI", "CPI", "dollar-value"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.472-2(e)",
        authority_type="regulation",
        title="LIFO Conformity — Permitted Supplemental Disclosures",
        year=1981,
        relevance="Supplemental LIFO reserve disclosures in financial statements do not violate conformity",
        key_holding="The conformity requirement is not violated by supplemental disclosure of inventory values on a non-LIFO basis in footnotes to financial statements, as long as the primary presentation uses LIFO. Disclosures required by SEC regulations, lenders, or other parties are similarly permitted.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "conformity", "supplemental disclosure", "LIFO reserve", "SEC"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.472-1",
        authority_type="regulation",
        title="LIFO Requirements — Permissible Methods",
        year=1981,
        relevance="LIFO may use any method acceptable under §471; must be consistently applied",
        key_holding="A taxpayer using LIFO must use a permissible method of inventory identification (specific identification, FIFO, or average cost for base year) and must consistently apply the method. The election applies to all goods in the pool and cannot be selectively applied to advantageous items.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["LIFO", "consistency", "permissible methods", "1.472-1"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.472-3",
        authority_type="regulation",
        title="LIFO Election — Time and Manner; Form 970",
        year=1981,
        relevance="LIFO election made on Form 970 attached to timely filed return for election year",
        key_holding="The LIFO election is made by attaching Form 970 (Application to Use LIFO Inventory Method) to the taxpayer's income tax return for the first year the LIFO method is to be used. The election must be filed no later than the due date (including extensions) of the return for the year of election.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "election", "Form 970", "timing", "1.472-3"],
    ),

    # --- LIFO Special Situations ---
    TechnicalAuthority(
        citation="IRC §1363(d)",
        authority_type="statute",
        title="LIFO Recapture on S Corporation Election",
        year=1987,
        relevance="C corporation with LIFO must include LIFO reserve in income when electing S status",
        key_holding="If a C corporation using LIFO elects S corporation status, the corporation must include the LIFO recapture amount (excess of FIFO inventory value over LIFO inventory value at end of last C year) in gross income. The tax attributable to the recapture is payable in 4 equal installments, with the first installment due with the last C corporation return.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["LIFO", "S corporation election", "LIFO recapture", "1363(d)"],
    ),
    TechnicalAuthority(
        citation="Rev. Proc. 79-23, 1979-1 C.B. 564",
        authority_type="rev_proc",
        title="LIFO Termination — Grounds for IRS-Initiated Termination",
        year=1979,
        relevance="IRS position on when it will terminate a taxpayer's LIFO election",
        key_holding="The IRS will terminate a taxpayer's LIFO election when: (1) the taxpayer fails to comply with the conformity requirement, (2) the taxpayer's books and records are inadequate to verify LIFO computations, or (3) the taxpayer uses methods that do not clearly reflect income. Termination is prospective unless fraud or misrepresentation is present.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["LIFO", "termination", "conformity", "Rev. Proc. 79-23", "IRS"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 79-290, 1979-2 C.B. 230",
        authority_type="rev_rul",
        title="Dollar-Value LIFO — Method of Valuation, Not Identification",
        year=1979,
        relevance="Dollar-value LIFO is a method of valuation, not a method of identification",
        key_holding="Dollar-value LIFO is characterized as a method of inventory valuation (comparing total dollar values), not a method of physical identification of goods. This means the LIFO conformity requirement does not prohibit separate identification of goods for other purposes, as long as the dollar-value method governs tax reporting.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "dollar-value", "valuation method", "identification"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 2001-8, 2001-1 C.B. 726",
        authority_type="rev_rul",
        title="Floor Stocks Taxes and LIFO Layers",
        year=2001,
        relevance="Floor stocks taxes (excise taxes on manufacturer's inventory) treated as period costs, not LIFO layer costs",
        key_holding="Floor stocks taxes imposed on a manufacturer's existing inventory when a new excise tax is enacted are deductible period costs under §162, not capitalizable costs that adjust LIFO inventory layers. The taxes do not represent an acquisition or production cost of the inventory.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "floor stocks tax", "excise tax", "period cost", "Rev. Rul. 2001-8"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 76-282, 1976-2 C.B. 136",
        authority_type="rev_rul",
        title="Restoration of Writedowns for Subnormal Goods Upon LIFO Adoption",
        year=1976,
        relevance="Prior writedowns of subnormal goods must be restored to income when LIFO is adopted",
        key_holding="When a taxpayer elects LIFO, any prior writedowns of inventory to market (including subnormal goods written down below cost) must be restored to income. The opening LIFO inventory must reflect cost, not the written-down market values. This is consistent with §472(b)'s requirement that opening LIFO inventory be valued at cost.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["LIFO", "subnormal goods", "writedown restoration", "election year", "Rev. Rul. 76-282"],
    ),
    TechnicalAuthority(
        citation="Rev. Rul. 70-564, 1970-2 C.B. 109",
        authority_type="rev_rul",
        title="LIFO Layers in §351 Transfers — Continuation",
        year=1970,
        relevance="LIFO history does not carry over to transferee corporation in §351 exchange",
        key_holding="When a taxpayer using LIFO transfers its inventory to a controlled corporation in a §351 exchange, the transferee corporation does not succeed to the transferor's LIFO history. The transferee corporation must establish new base-year inventory values. The transferred inventory is treated as acquired by the transferee at the transferred basis.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["LIFO", "351 transfer", "basis", "LIFO layers", "carryover"],
    ),
    TechnicalAuthority(
        citation="Rev. Proc. 2008-23, 2008-1 C.B. 444",
        authority_type="rev_proc",
        title="LIFO Pooling — Auto Dealers",
        year=2008,
        relevance="Auto dealers may use separate LIFO pools for new vehicles, used vehicles, and parts",
        key_holding="Automobile dealers using LIFO may maintain separate pools for new vehicles, used vehicles, and parts and accessories. Provides specific guidance on how to establish base-year values and compute LIFO increments/decrements for each pool type.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["LIFO", "pooling", "auto dealers", "vehicles", "Rev. Proc. 2008-23"],
    ),
    TechnicalAuthority(
        citation="IRC §312(n)(4)",
        authority_type="statute",
        title="LIFO Adjustment to Earnings and Profits",
        year=1986,
        relevance="E&P computed using FIFO when taxpayer uses LIFO for taxable income",
        key_holding="For purposes of computing earnings and profits, inventory is valued under the FIFO method rather than LIFO. The LIFO reserve (excess of FIFO over LIFO value) reduces E&P. This prevents LIFO from being used to artificially reduce distributions treated as dividends.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["LIFO", "earnings and profits", "E&P", "FIFO", "312(n)(4)"],
    ),
    TechnicalAuthority(
        citation="IRC §381(c)(5)",
        authority_type="statute",
        title="LIFO Method Carryover in Corporate Acquisitions",
        year=1986,
        relevance="Acquiring corporation in §381 transaction may continue LIFO method of acquired corporation",
        key_holding="In a §381 transaction (§332 liquidation, §368 reorganization), the acquiring corporation succeeds to the inventory method of the acquired corporation, including LIFO. The acquiring corporation must continue LIFO unless it obtains consent to change methods.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["LIFO", "381", "carryover", "corporate acquisition", "reorganization"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.381(c)(5)-1",
        authority_type="regulation",
        title="Inventory Method Carryovers — §381 Transactions",
        year=1967,
        relevance="Detailed rules for carryover of inventory methods in corporate acquisitions",
        key_holding="When a corporation acquires assets in a §381 transaction, it must use the inventory method of the transferor with respect to the acquired inventory. If the acquiring and acquired corporations used different methods, the acquiring corporation must adopt a single method as quickly as possible, generally within the year of acquisition.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["381", "inventory method", "carryover", "acquisition", "method change"],
    ),
]
