"""UNICAP (§263A) detailed technical authorities.

Covers the full regulatory framework under §263A including simplified
methods, interest capitalization, mixed service costs, specific cost
categories, and industry-specific rules.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from revenue_recognition.technical_authority.authorities.base import TechnicalAuthority

UNICAP_AUTHORITIES = [
    # --- Core §263A Statute ---
    TechnicalAuthority(
        citation="IRC §263A(f)",
        authority_type="statute",
        title="§263A Interest Capitalization Rules",
        year=1986,
        relevance="Interest costs must be capitalized to the extent allocable to property requiring extended production period",
        key_holding="Interest paid or incurred during the production period of property with a production period exceeding 2 years (or 1 year if cost exceeds $1M) must be capitalized. The capitalized interest is allocated to the property based on accumulated production expenditures. Applies to real property, ships, aircraft, and certain other property.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "interest capitalization", "263A(f)", "production period", "self-constructed assets"],
    ),
    TechnicalAuthority(
        citation="IRC §263A(b)(2)",
        authority_type="statute",
        title="§263A — Property Produced Under Long-Term Contracts",
        year=1986,
        relevance="Long-term contracts subject to §460 are excluded from §263A",
        key_holding="§263A does not apply to property produced by the taxpayer pursuant to a long-term contract (as defined in §460). Such property is governed exclusively by the long-term contract methods (PCM or CCM under §460).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "long-term contracts", "460", "exclusion"],
    ),
    TechnicalAuthority(
        citation="IRC §263A(c)(4)",
        authority_type="statute",
        title="§263A — Farming Exclusion",
        year=1986,
        relevance="Farming businesses exempt from §263A for certain plants and animals",
        key_holding="§263A does not apply to any animal, or any plant with a preproductive period of 2 years or less. For plants with longer preproductive periods, §263A applies unless the taxpayer elects out under §263A(d)(3) (available to certain farming taxpayers not required to use accrual method).",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "farming", "preproductive period", "exclusion", "263A(c)(4)"],
    ),

    # --- UNICAP Regulations — Core ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(e)(2)",
        authority_type="regulation",
        title="UNICAP — Direct Costs",
        year=1993,
        relevance="Direct costs that must be capitalized under §263A",
        key_holding="Direct costs include: (1) direct material costs (cost of materials used in production), and (2) direct labor costs (costs of labor that can be identified or associated with particular property). Direct materials include raw materials, purchased components, and packaging materials. Direct labor includes wages of production workers.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "direct costs", "direct materials", "direct labor", "UNICAP"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(e)(3)",
        authority_type="regulation",
        title="UNICAP — Indirect Costs — Capitalizable Categories",
        year=1993,
        relevance="Comprehensive list of indirect costs that must be capitalized to inventory",
        key_holding="Indirect costs required to be capitalized include: (1) repair and maintenance of equipment, (2) utilities, (3) rent, (4) indirect materials and supplies, (5) tools and equipment, (6) quality control and inspection, (7) depreciation, (8) depletion, (9) amortization, (10) employee benefits, (11) officers' compensation, (12) purchasing costs, (13) handling/processing/assembly costs, (14) storage costs (excluding off-site), (15) cost recovery deductions (§168, §179), (16) taxes other than income taxes.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "indirect costs", "capitalizable", "UNICAP", "1.263A-1(e)(3)"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(e)(4)",
        authority_type="regulation",
        title="UNICAP — Non-Capitalizable Costs",
        year=1993,
        relevance="Costs specifically excluded from §263A capitalization requirement",
        key_holding="The following costs are NOT required to be capitalized under §263A: (1) marketing, selling, advertising, and distribution costs, (2) bidding costs (unsuccessful bids), (3) research and experimental costs (§174), (4) §165 losses, (5) income taxes, (6) costs attributable to strikes, (7) excess capacity costs (idle plant/equipment), (8) warranty expense, (9) on-site storage costs for property that is not inventory, (10) deductible service costs.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "non-capitalizable", "selling costs", "R&D", "idle capacity", "1.263A-1(e)(4)"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(f)",
        authority_type="regulation",
        title="UNICAP — Methods of Allocation",
        year=1993,
        relevance="Permissible methods for allocating indirect costs to produced property",
        key_holding="Taxpayers may use any reasonable method to allocate indirect costs, including: (1) specific identification, (2) burden rate allocation, (3) standard cost method, (4) simplified production method, (5) simplified service cost method, or (6) any other reasonable method. The method must clearly reflect income and must be consistently applied.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "allocation methods", "burden rate", "standard cost", "1.263A-1(f)"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(g)",
        authority_type="regulation",
        title="UNICAP — Mixed Service Costs",
        year=1993,
        relevance="Service department costs that partially benefit production and partially benefit non-production activities",
        key_holding="Mixed service costs are indirect costs incurred in service departments or functions that serve both production/resale activities and non-production activities. These costs must be allocated between capitalizable and deductible portions. Allocation may use direct reallocation, step-down, or reciprocal methods, or the simplified service cost method.",
        facts_summary="Examples of mixed service departments include: HR/personnel, accounting, IT, legal, security, executive management. The most contentious issue is determining the proper split of mixed service costs.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "mixed service costs", "service departments", "allocation", "1.263A-1(g)"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-1(h)",
        authority_type="regulation",
        title="UNICAP — Simplified Service Cost Method",
        year=1993,
        relevance="Alternative simplified method for allocating service costs using labor or gross receipts ratio",
        key_holding="Under the simplified service cost method, a taxpayer allocates mixed service costs to produced property using a labor-based or gross receipts-based allocation ratio. The ratio compares labor costs (or gross receipts) attributable to production activities to total labor costs (or gross receipts). Reduces complexity of mixed service cost allocation.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "simplified service cost method", "labor ratio", "gross receipts ratio"],
    ),

    # --- UNICAP Producers (§1.263A-2) ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-2(a)",
        authority_type="regulation",
        title="UNICAP — Property Produced by Taxpayer",
        year=1993,
        relevance="Rules for producers — what constitutes production and what costs are capitalized",
        key_holding="A taxpayer is treated as producing property if the taxpayer manufactures, constructs, builds, installs, improves, develops, creates, raises, or grows the property. Production includes causing property to be produced under contract where taxpayer bears economic risk. Licensing arrangements may also constitute production depending on facts.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "producer", "production", "contract manufacturing", "1.263A-2"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-2(b)(2)",
        authority_type="regulation",
        title="UNICAP — Simplified Production Method",
        year=1993,
        relevance="Simplified method for producers using absorption ratio applied to ending inventory",
        key_holding="Under the simplified production method, a taxpayer computes an 'absorption ratio' equal to additional §263A costs divided by §471 costs (less direct materials). This ratio is multiplied by §471 costs in ending inventory to determine the §263A adjustment. The method simplifies the tracking of individual costs to specific inventory items.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "simplified production method", "absorption ratio", "producers"],
    ),

    # --- UNICAP Resellers (§1.263A-3) ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-3(a)",
        authority_type="regulation",
        title="UNICAP — Reseller Rules",
        year=1993,
        relevance="Rules for taxpayers acquiring property for resale — purchasing and storage costs",
        key_holding="Resellers must capitalize purchasing costs (vendor selection, order placement, expediting) and off-site storage and handling costs. On-site storage at a retail store is excluded. Costs of processing, repackaging, or assembling goods for resale are capitalizable.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "reseller", "purchasing costs", "storage", "handling", "1.263A-3"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-3(c)(5)",
        authority_type="regulation",
        title="UNICAP — Simplified Resale Method",
        year=1993,
        relevance="Simplified method for resellers using combined absorption ratio",
        key_holding="Under the simplified resale method, a reseller computes a combined absorption ratio equal to capitalizable purchasing/storage/handling costs divided by (beginning inventory + purchases). This ratio is applied to ending inventory to determine the §263A adjustment. Generally favorable for resellers with significant purchasing operations.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "simplified resale method", "resellers", "combined ratio"],
    ),

    # --- Farming (§1.263A-4) ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-4",
        authority_type="regulation",
        title="UNICAP — Property Produced in Farming Business",
        year=1993,
        relevance="Application of §263A to farming businesses — preproductive period costs",
        key_holding="§263A applies to plants with preproductive periods exceeding 2 years (e.g., orchards, vineyards, timber). Capitalizable costs include planting, cultivating, watering, fertilizing, and other maintenance costs during the preproductive period. Special rules apply to replanting after disaster losses.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A", "farming", "preproductive period", "crops", "orchards", "1.263A-4"],
    ),

    # --- Interest Capitalization (§1.263A-8 through -15) ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-8",
        authority_type="regulation",
        title="§263A(f) Interest Capitalization — Scope and Definitions",
        year=1992,
        relevance="Interest must be capitalized to self-constructed assets meeting production period requirements",
        key_holding="Interest paid or incurred during the production period must be capitalized for: (1) designated property (real property or tangible personal property with production period >2 years or cost >$1M), and (2) property requiring more than one year to produce. The capitalized interest is included in the property's basis.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A(f)", "interest capitalization", "designated property", "production period", "1.263A-8"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-9",
        authority_type="regulation",
        title="§263A(f) — Avoided Cost Method for Interest Capitalization",
        year=1992,
        relevance="Interest capitalized equals interest that could have been avoided had accumulated expenditures been used to repay debt",
        key_holding="Under the avoided cost method, the interest capitalized to a designated property equals the interest cost that the taxpayer would have avoided had accumulated production expenditures been used to repay outstanding indebtedness. The method traces avoided interest through a hierarchy of traced and allocated debt.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A(f)", "avoided cost method", "interest capitalization", "accumulated expenditures", "1.263A-9"],
    ),
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-11",
        authority_type="regulation",
        title="§263A(f) — Accumulated Production Expenditures",
        year=1992,
        relevance="Definition and computation of accumulated production expenditures for interest capitalization",
        key_holding="Accumulated production expenditures are the cumulative amount of direct costs and indirect costs (including previously capitalized interest) allocable to designated property through the measurement date. Includes costs of materials, labor, overhead, and other capitalizable costs incurred in prior years.",
        taxpayer_favorable=False,
        weight="primary",
        topics=["263A(f)", "accumulated production expenditures", "measurement date", "1.263A-11"],
    ),

    # --- UNICAP Method Changes ---
    TechnicalAuthority(
        citation="Treas. Reg. §1.263A-7",
        authority_type="regulation",
        title="§263A — Changing Methods under §263A",
        year=1993,
        relevance="Rules for changing §263A cost allocation methods",
        key_holding="A change in the method used to determine §263A costs is a change in method of accounting requiring either automatic or advance consent under §446. A change that results in a more accurate allocation of indirect costs may be made with automatic consent. Changes from a simplified method to a specific identification method generally require advance consent.",
        taxpayer_favorable=True,
        weight="primary",
        topics=["263A", "method change", "accounting method", "Form 3115", "1.263A-7"],
    ),

    # --- Notices ---
    TechnicalAuthority(
        citation="Notice 88-86, 1988-2 C.B. 401",
        authority_type="notice",
        title="UNICAP — Interpretive Guidance on Storage Costs, Mixed Service Costs",
        year=1988,
        relevance="IRS guidance on specific categories of capitalizable and non-capitalizable costs under §263A",
        key_holding="Clarifies that: (1) off-site storage costs are capitalizable while on-site retail storage is not, (2) mixed service department costs must be allocated between capitalizable and non-capitalizable activities, (3) certain administrative costs with a direct connection to production are capitalizable even if not listed in the regulations. Provides examples of proper allocation techniques.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["263A", "storage costs", "mixed service costs", "Notice 88-86", "allocation"],
    ),
    TechnicalAuthority(
        citation="Notice 88-99, 1988-2 C.B. 422",
        authority_type="notice",
        title="§263A(f) Interest Capitalization — Initial Guidance",
        year=1988,
        relevance="Initial IRS guidance on interest capitalization rules under §263A(f)",
        key_holding="Provides preliminary guidance on the interest capitalization rules, including definitions of designated property, the production period, and accumulated production expenditures. Indicates IRS's intention to issue regulations and describes the avoided cost methodology that will be required.",
        taxpayer_favorable=False,
        weight="substantial",
        topics=["263A(f)", "interest capitalization", "Notice 88-99", "designated property"],
    ),
    TechnicalAuthority(
        citation="Notice 89-67, 1989-1 C.B. 722",
        authority_type="notice",
        title="UNICAP — Amendments to §263A by Technical Corrections Act of 1988",
        year=1989,
        relevance="Guidance on 1988 technical corrections to UNICAP including storage cost rules and farming exceptions",
        key_holding="Addresses amendments to §263A made by the Technical and Miscellaneous Revenue Act of 1988, including: (1) clarification of off-site storage cost rules, (2) expansion of the farming election out of §263A, (3) modifications to the preproductive period rules, and (4) changes to the definition of property to which §263A applies.",
        taxpayer_favorable=True,
        weight="substantial",
        topics=["263A", "UNICAP", "Notice 89-67", "1988 amendments", "storage", "farming"],
    ),
    TechnicalAuthority(
        citation="LB&I Concept Unit — Examining a Reseller's IRC 263A Computation",
        authority_type="other",
        title="LB&I Practice Unit — Reseller UNICAP Computation",
        year=2015,
        relevance="IRS audit focus areas for examining reseller §263A computations",
        key_holding="Key IRS audit concerns for reseller UNICAP: (1) proper identification of off-site storage costs vs. on-site storage, (2) allocation of purchasing department costs (qualifying vs. non-qualifying activities), (3) handling costs distinction between production and mere transportation, (4) proper application of simplified resale method, (5) inclusion of freight and shipping department costs.",
        taxpayer_favorable=False,
        weight="some",
        topics=["263A", "reseller", "LB&I", "audit", "storage", "purchasing costs"],
    ),
    TechnicalAuthority(
        citation="LB&I Concept Unit — Producer's 263A Computation",
        authority_type="other",
        title="LB&I Practice Unit — Producer UNICAP Computation",
        year=2015,
        relevance="IRS audit focus areas for examining producer §263A computations",
        key_holding="Key IRS audit concerns for producer UNICAP: (1) proper classification of mixed service costs, (2) identification of all indirect production costs, (3) correct application of simplified production method (particularly the absorption ratio denominator), (4) treatment of idle capacity costs, (5) quality control cost capitalization, (6) depreciation inclusion in UNICAP costs.",
        taxpayer_favorable=False,
        weight="some",
        topics=["263A", "producer", "LB&I", "audit", "mixed service costs", "indirect costs"],
    ),
]
