"""Writer stage - formats analysis into polished investment proposals.

Takes the AnalysisResult from the Analyst stage and produces a
formatted Markdown proposal document.
"""

import json
import os
from datetime import datetime
from typing import Optional

import anthropic

from .analyst import AnalysisResult
from .researcher import ResearchBundle, ResearchStage


WRITER_SYSTEM_PROMPT = """You are an investment research writer who produces clear,
professional investment proposals. Your writing is concise, data-driven, and
accessible to both experienced investors and beginners.

FORMATTING RULES:
- Use clear section headers
- Include data tables where appropriate
- Bold key numbers and conclusions
- Keep language professional but not jargon-heavy
- Always include the disclaimer at the end

DISCLAIMER (always include verbatim at end):
---
**DISCLAIMER**: This proposal is generated by an AI system for educational and research
purposes only. It does not constitute financial advice, a recommendation to buy or sell
any security, or an offer of any kind. Past performance is not indicative of future results.
Always consult a qualified financial advisor before making investment decisions.
---"""

WRITER_USER_PROMPT = """Write a polished investment proposal in Markdown format using the
analysis data below. Make it visually clean, well-structured, and actionable.

ANALYSIS DATA:
{analysis_json}

ADDITIONAL MARKET CONTEXT:
{market_context}

Structure the proposal as:
1. Executive Summary (2-3 sentences, the thesis + rating)
2. Company Overview (sector, industry, market cap - brief)
3. Quantitative Breakdown (table of key metrics)
4. Valuation Analysis
5. Growth Outlook
6. Risk Assessment
7. Tax & Portfolio Considerations
8. Bull Case / Bear Case (side by side if possible)
9. Recommendation (the final verdict with confidence level)
10. Disclaimer

Write the complete Markdown document now."""


class WriterStage:
    """Produces polished investment proposal documents.

    Args:
        api_key: Anthropic API key. Falls back to ANTHROPIC_API_KEY env var.
        model: Claude model to use.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "claude-sonnet-4-20250514",
    ):
        self.client = anthropic.Anthropic(
            api_key=api_key or os.getenv("ANTHROPIC_API_KEY")
        )
        self.model = model

    def write_proposal(
        self,
        analysis: AnalysisResult,
        bundle: Optional[ResearchBundle] = None,
        research_stage: Optional[ResearchStage] = None,
    ) -> str:
        """Generate a formatted investment proposal.

        Args:
            analysis: AnalysisResult from the analyst stage.
            bundle: Optional research bundle for additional context.
            research_stage: Optional research stage for formatting.

        Returns:
            Complete Markdown proposal document.
        """
        analysis_json = json.dumps(
            {
                "ticker": analysis.ticker,
                "company_name": analysis.company_name,
                "investment_thesis": analysis.investment_thesis,
                "valuation_assessment": analysis.valuation_assessment,
                "risk_analysis": analysis.risk_analysis,
                "growth_outlook": analysis.growth_outlook,
                "tax_considerations": analysis.tax_considerations,
                "bear_case": analysis.bear_case,
                "bull_case": analysis.bull_case,
                "overall_rating": analysis.overall_rating,
                "confidence_level": analysis.confidence_level,
                "key_metrics_summary": analysis.key_metrics_summary,
            },
            indent=2,
        )

        market_context = ""
        if bundle and research_stage:
            if bundle.snapshot:
                market_context += research_stage.market.format_snapshot_text(bundle.snapshot)
            if bundle.historical:
                market_context += research_stage.market.format_historical_text(bundle.historical)

        message = self.client.messages.create(
            model=self.model,
            max_tokens=4096,
            system=WRITER_SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": WRITER_USER_PROMPT.format(
                        analysis_json=analysis_json,
                        market_context=market_context or "No additional context available.",
                    ),
                }
            ],
        )

        proposal = message.content[0].text.strip()

        # Add generation metadata header
        header = (
            f"<!-- Generated by AI Investment Analyzer | "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M UTC')} | "
            f"Model: {self.model} -->\n\n"
        )

        return header + proposal

    def write_proposal_static(self, analysis: AnalysisResult) -> str:
        """Generate a proposal using templates without an LLM call.

        Useful for testing or when API credits need to be conserved.
        """
        metrics = analysis.key_metrics_summary
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        return f"""<!-- Generated by AI Investment Analyzer | {now} | Static Template -->

# Investment Proposal: {analysis.company_name} ({analysis.ticker})

**Rating: {analysis.overall_rating}** | Confidence: {analysis.confidence_level}
**Generated**: {now}

---

## Executive Summary

{analysis.investment_thesis}

---

## Quantitative Breakdown

| Metric | Value |
|--------|-------|
| Current Price | {metrics.get('current_price', 'N/A')} |
| Fair Value Estimate | {metrics.get('fair_value_estimate', 'N/A')} |
| P/E vs Sector | {metrics.get('pe_vs_sector_avg', 'N/A')} |
| Key Strength | {metrics.get('key_strength', 'N/A')} |
| Key Risk | {metrics.get('key_risk', 'N/A')} |

---

## Valuation Analysis

{analysis.valuation_assessment}

---

## Growth Outlook

{analysis.growth_outlook}

---

## Risk Assessment

{analysis.risk_analysis}

---

## Tax & Portfolio Considerations

{analysis.tax_considerations}

---

## Bull Case

{analysis.bull_case}

## Bear Case

{analysis.bear_case}

---

## Recommendation

**{analysis.overall_rating}** (Confidence: {analysis.confidence_level})

{analysis.investment_thesis}

---

**DISCLAIMER**: This proposal is generated by an AI system for educational and research
purposes only. It does not constitute financial advice, a recommendation to buy or sell
any security, or an offer of any kind. Past performance is not indicative of future results.
Always consult a qualified financial advisor before making investment decisions.
"""
